//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.administration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.administration.AdminRes", typeof(AdminRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~r~[Admin}~w~ {0} has brought you to his position..
        /// </summary>
        public static string bring_player {
            get {
                return ResourceManager.GetString("bring_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve changed to &apos;{0}&apos; the business&apos; name..
        /// </summary>
        public static string business_name_modified {
            get {
                return ResourceManager.GetString("business_name_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve changed to &apos;{0}&apos; the business&apos;type..
        /// </summary>
        public static string business_type_modified {
            get {
                return ResourceManager.GetString("business_type_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the characters saved..
        /// </summary>
        public static string characters_saved {
            get {
                return ResourceManager.GetString("characters_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve toggled off God mode..
        /// </summary>
        public static string god_mode_off {
            get {
                return ResourceManager.GetString("god_mode_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re now in God mode..
        /// </summary>
        public static string god_mode_on {
            get {
                return ResourceManager.GetString("god_mode_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve teleported to {0}&apos;s position..
        /// </summary>
        public static string goto_player {
            get {
                return ResourceManager.GetString("goto_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve created a house in your position..
        /// </summary>
        public static string house_created {
            get {
                return ResourceManager.GetString("house_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve deleted the closest house..
        /// </summary>
        public static string house_deleted {
            get {
                return ResourceManager.GetString("house_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve changed to &apos;{0}&apos; the house&apos;s dimension..
        /// </summary>
        public static string house_interior_modified {
            get {
                return ResourceManager.GetString("house_interior_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is the new address of this house..
        /// </summary>
        public static string house_name_modified {
            get {
                return ResourceManager.GetString("house_name_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is the new owner of this house..
        /// </summary>
        public static string house_owner_modified {
            get {
                return ResourceManager.GetString("house_owner_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve changed to &apos;{0}&apos; the house&apos;s price..
        /// </summary>
        public static string house_price_modified {
            get {
                return ResourceManager.GetString("house_price_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve changed to {0}$ the house&apos;s rental price..
        /// </summary>
        public static string house_rental_modified {
            get {
                return ResourceManager.GetString("house_rental_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve changed to &apos;{0}&apos; the house&apos;s state..
        /// </summary>
        public static string house_status_modified {
            get {
                return ResourceManager.GetString("house_status_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the players have been kicked from the server..
        /// </summary>
        public static string kicked_all {
            get {
                return ResourceManager.GetString("kicked_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a new incomming assistant ticket..
        /// </summary>
        public static string new_admin_ticket {
            get {
                return ResourceManager.GetString("new_admin_ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve created a parking in your position..
        /// </summary>
        public static string parking_created {
            get {
                return ResourceManager.GetString("parking_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve deleted the closest parking..
        /// </summary>
        public static string parking_deleted {
            get {
                return ResourceManager.GetString("parking_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve linked the house {0} to this parking..
        /// </summary>
        public static string parking_house_modified {
            get {
                return ResourceManager.GetString("parking_house_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking {0} - Information:.
        /// </summary>
        public static string parking_info {
            get {
                return ResourceManager.GetString("parking_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve changed to {0} this parking&apos;s maximum slots..
        /// </summary>
        public static string parking_slots_modified {
            get {
                return ResourceManager.GetString("parking_slots_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve change to &apos;{0}&apos; the parking&apos;s type..
        /// </summary>
        public static string parking_type_modified {
            get {
                return ResourceManager.GetString("parking_type_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve change to {0}$ {1}&apos;s bank money..
        /// </summary>
        public static string player_bank_modified {
            get {
                return ResourceManager.GetString("player_bank_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} banned {1} from the server. Reason: {2}.
        /// </summary>
        public static string player_banned {
            get {
                return ResourceManager.GetString("player_banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve changed to &apos;{0}&apos; {1}&apos;s dimension..
        /// </summary>
        public static string player_dimension_modified {
            get {
                return ResourceManager.GetString("player_dimension_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve changed to &apos;{0}&apos; {1}&apos;s faction..
        /// </summary>
        public static string player_faction_modified {
            get {
                return ResourceManager.GetString("player_faction_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You changed {0}&apos;s health to {1}..
        /// </summary>
        public static string player_health {
            get {
                return ResourceManager.GetString("player_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been jailed for {1} minutes. Reason: {2}.
        /// </summary>
        public static string player_jailed {
            get {
                return ResourceManager.GetString("player_jailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve changed to &apos;{0}&apos; {1}&apos;s job..
        /// </summary>
        public static string player_job_modified {
            get {
                return ResourceManager.GetString("player_job_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kicked {1} from the server. Reason: {2}.
        /// </summary>
        public static string player_kicked {
            get {
                return ResourceManager.GetString("player_kicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve change to {0}$ {1}&apos;s hand money..
        /// </summary>
        public static string player_money_modified {
            get {
                return ResourceManager.GetString("player_money_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve changed to &apos;{0}&apos; {1}&apos;s faction rank..
        /// </summary>
        public static string player_rank_modified {
            get {
                return ResourceManager.GetString("player_rank_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve revived {0}..
        /// </summary>
        public static string player_revived {
            get {
                return ResourceManager.GetString("player_revived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} set to {1} your role points..
        /// </summary>
        public static string role_points_established {
            get {
                return ResourceManager.GetString("role_points_established", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve given {0} role points to {1}..
        /// </summary>
        public static string role_points_given {
            get {
                return ResourceManager.GetString("role_points_given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} removed you {1} role points..
        /// </summary>
        public static string role_points_lost {
            get {
                return ResourceManager.GetString("role_points_lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gave you {1} role points..
        /// </summary>
        public static string role_points_received {
            get {
                return ResourceManager.GetString("role_points_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve removed {0} role points to {1}..
        /// </summary>
        public static string role_points_removed {
            get {
                return ResourceManager.GetString("role_points_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve set to {0} {1}&apos;s role points..
        /// </summary>
        public static string role_points_set {
            get {
                return ResourceManager.GetString("role_points_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} business have been updated..
        /// </summary>
        public static string save_business {
            get {
                return ResourceManager.GetString("save_business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity saving finished..
        /// </summary>
        public static string save_finish {
            get {
                return ResourceManager.GetString("save_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} parkings have been updated..
        /// </summary>
        public static string save_parkings {
            get {
                return ResourceManager.GetString("save_parkings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving all entities in the world....
        /// </summary>
        public static string save_start {
            get {
                return ResourceManager.GetString("save_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve stopped spectating..
        /// </summary>
        public static string spect_stopped {
            get {
                return ResourceManager.GetString("spect_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re spectating {0}..
        /// </summary>
        public static string spectating_player {
            get {
                return ResourceManager.GetString("spectating_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed your health to {1}..
        /// </summary>
        public static string target_health {
            get {
                return ResourceManager.GetString("target_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You answered the ticket number &apos;{0}&apos;..
        /// </summary>
        public static string ticket_answered {
            get {
                return ResourceManager.GetString("ticket_answered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You brought the {0} vehicle to your position..
        /// </summary>
        public static string vehicle_bring {
            get {
                return ResourceManager.GetString("vehicle_bring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve changed to &apos;{0}&apos; the vehicle&apos;s dimension..
        /// </summary>
        public static string vehicle_dimension_modified {
            get {
                return ResourceManager.GetString("vehicle_dimension_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve changed to &apos;{0}&apos; the vehicle&apos;s faction..
        /// </summary>
        public static string vehicle_faction_modified {
            get {
                return ResourceManager.GetString("vehicle_faction_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You teleported to the vehicle {0}..
        /// </summary>
        public static string vehicle_goto {
            get {
                return ResourceManager.GetString("vehicle_goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve changed to &apos;{0}&apos; the vehicle&apos;s owner..
        /// </summary>
        public static string vehicle_owner_modified {
            get {
                return ResourceManager.GetString("vehicle_owner_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve updated the vehicle&apos;s position..
        /// </summary>
        public static string vehicle_pos_updated {
            get {
                return ResourceManager.GetString("vehicle_pos_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You repaired the vehicle..
        /// </summary>
        public static string vehicle_repaired {
            get {
                return ResourceManager.GetString("vehicle_repaired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the vehicles saved..
        /// </summary>
        public static string vehicles_saved {
            get {
                return ResourceManager.GetString("vehicles_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon&apos;s event has started..
        /// </summary>
        public static string weapon_event_started {
            get {
                return ResourceManager.GetString("weapon_event_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has changed the weather value to &apos;{1}&apos;..
        /// </summary>
        public static string weather_changed {
            get {
                return ResourceManager.GetString("weather_changed", resourceCulture);
            }
        }
    }
}
