//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.success {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuccRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.success.SuccRes", typeof(SuccRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~r~[Admin]~w~ {0} has revived you..
        /// </summary>
        public static string admin_revived {
            get {
                return ResourceManager.GetString("admin_revived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new ticket has been generated, wait for a staff member to answer it..
        /// </summary>
        public static string help_request_sent {
            get {
                return ResourceManager.GetString("help_request_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve finished with this client..
        /// </summary>
        public static string hooker_client_satisfied {
            get {
                return ResourceManager.GetString("hooker_client_satisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hooker&apos;s service has finished..
        /// </summary>
        public static string hooker_service_finished {
            get {
                return ResourceManager.GetString("hooker_service_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sold yous house for {0}$.
        /// </summary>
        public static string house_sold {
            get {
                return ResourceManager.GetString("house_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} accepted your interview request..
        /// </summary>
        public static string interview_accepted {
            get {
                return ResourceManager.GetString("interview_accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your client has gotten a reduced jail time..
        /// </summary>
        public static string lawyer_client_satisfied {
            get {
                return ResourceManager.GetString("lawyer_client_satisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lawyer has reduced the jail time. .
        /// </summary>
        public static string lawyer_service_finished {
            get {
                return ResourceManager.GetString("lawyer_service_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You passed the practical exam..
        /// </summary>
        public static string license_drive_passed {
            get {
                return ResourceManager.GetString("license_drive_passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You passed the theoric exam..
        /// </summary>
        public static string license_exam_passed {
            get {
                return ResourceManager.GetString("license_exam_passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully lockpicked..
        /// </summary>
        public static string lockpicked {
            get {
                return ResourceManager.GetString("lockpicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} had a possitive result..
        /// </summary>
        public static string possitive_result {
            get {
                return ResourceManager.GetString("possitive_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The doctor {0} reanimated you..
        /// </summary>
        public static string target_reanimated {
            get {
                return ResourceManager.GetString("target_reanimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You managed to hotwire the vehicle..
        /// </summary>
        public static string veh_hotwireed {
            get {
                return ResourceManager.GetString("veh_hotwireed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locked the vehicle..
        /// </summary>
        public static string veh_locked {
            get {
                return ResourceManager.GetString("veh_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlocked the vehicle..
        /// </summary>
        public static string veh_unlocked {
            get {
                return ResourceManager.GetString("veh_unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You purchased your vehicle..
        /// </summary>
        public static string vehicle_purchased {
            get {
                return ResourceManager.GetString("vehicle_purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received {0}$ for scrapping your vehicle..
        /// </summary>
        public static string vehicle_scrapyard {
            get {
                return ResourceManager.GetString("vehicle_scrapyard", resourceCulture);
            }
        }
    }
}
