//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.error {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.error.ErrRes", typeof(ErrRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already wearing an accessory..
        /// </summary>
        public static string accessory_equiped {
            get {
                return ResourceManager.GetString("accessory_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ticket was found with that identifier..
        /// </summary>
        public static string admin_ticket_not_found {
            get {
                return ResourceManager.GetString("admin_ticket_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This vehicle can only be accessed by the staff..
        /// </summary>
        public static string admin_vehicle {
            get {
                return ResourceManager.GetString("admin_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re in the middle of a service with your client..
        /// </summary>
        public static string already_fucking {
            get {
                return ResourceManager.GetString("already_fucking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already collecting garbage..
        /// </summary>
        public static string already_garbage {
            get {
                return ResourceManager.GetString("already_garbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re in the middle of a job route..
        /// </summary>
        public static string already_in_route {
            get {
                return ResourceManager.GetString("already_in_route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already lockpicking..
        /// </summary>
        public static string already_lockpicking {
            get {
                return ResourceManager.GetString("already_lockpicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a radio channel created..
        /// </summary>
        public static string already_owned_channel {
            get {
                return ResourceManager.GetString("already_owned_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already talking to the phone..
        /// </summary>
        public static string already_phone_talking {
            get {
                return ResourceManager.GetString("already_phone_talking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already testing a vehicle..
        /// </summary>
        public static string already_testing_vehicle {
            get {
                return ResourceManager.GetString("already_testing_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already wearing a bag..
        /// </summary>
        public static string bag_equiped {
            get {
                return ResourceManager.GetString("bag_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no bank account linked to that person..
        /// </summary>
        public static string bank_account_not_found {
            get {
                return ResourceManager.GetString("bank_account_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing the operation..
        /// </summary>
        public static string bank_general_error {
            get {
                return ResourceManager.GetString("bank_general_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank account has not enough funds to process the operation..
        /// </summary>
        public static string bank_not_enough_money {
            get {
                return ResourceManager.GetString("bank_not_enough_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have an item in your hands..
        /// </summary>
        public static string both_hand_occupied {
            get {
                return ResourceManager.GetString("both_hand_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no clothes for sale..
        /// </summary>
        public static string business_clothes_not_available {
            get {
                return ResourceManager.GetString("business_clothes_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This business is locked..
        /// </summary>
        public static string business_locked {
            get {
                return ResourceManager.GetString("business_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The business is not for sale..
        /// </summary>
        public static string business_not_buyable {
            get {
                return ResourceManager.GetString("business_not_buyable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have enough money to purchase this business.
        /// </summary>
        public static string business_not_money {
            get {
                return ResourceManager.GetString("business_not_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t sell the vehicle to yourself..
        /// </summary>
        public static string cant_sell_vehicle_self {
            get {
                return ResourceManager.GetString("cant_sell_vehicle_self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to wait before sending a new ticket..
        /// </summary>
        public static string cant_send_multiple_help_requests {
            get {
                return ResourceManager.GetString("cant_send_multiple_help_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t spectate yourself..
        /// </summary>
        public static string cant_spect_self {
            get {
                return ResourceManager.GetString("cant_spect_self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t turn the engine on while having a sex service..
        /// </summary>
        public static string cant_toogle_engine_while_fucking {
            get {
                return ResourceManager.GetString("cant_toogle_engine_while_fucking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a car license..
        /// </summary>
        public static string car_license_achieved {
            get {
                return ResourceManager.GetString("car_license_achieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need at least {0}$ in your bank account to purchase this vehicle..
        /// </summary>
        public static string carshop_no_money {
            get {
                return ResourceManager.GetString("carshop_no_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the parking places of the car dealer are occupied..
        /// </summary>
        public static string carshop_spawn_occupied {
            get {
                return ResourceManager.GetString("carshop_spawn_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You couldn&apos;t connect to the radio frequency channel..
        /// </summary>
        public static string channel_not_found {
            get {
                return ResourceManager.GetString("channel_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client must be on driver&apos;s seat..
        /// </summary>
        public static string client_not_vehicle_driving {
            get {
                return ResourceManager.GetString("client_not_vehicle_driving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any contact in your contact list..
        /// </summary>
        public static string contact_list_empty {
            get {
                return ResourceManager.GetString("contact_list_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get down from the motorcycle to deliver the order..
        /// </summary>
        public static string deliver_in_vehicle {
            get {
                return ResourceManager.GetString("deliver_in_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need {0}$ to examinate..
        /// </summary>
        public static string driving_school_money {
            get {
                return ResourceManager.GetString("driving_school_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already wearing a pair of earrings..
        /// </summary>
        public static string ear_equiped {
            get {
                return ResourceManager.GetString("ear_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to get {0} more paydays to leave the job..
        /// </summary>
        public static string employee_cooldown {
            get {
                return ResourceManager.GetString("employee_cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This vehicle&apos;s engine is already toggled on..
        /// </summary>
        public static string engine_already_started {
            get {
                return ResourceManager.GetString("engine_already_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to toggle the vehicle engine off..
        /// </summary>
        public static string engine_on {
            get {
                return ResourceManager.GetString("engine_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not enough funds into the faction&apos;s coffers..
        /// </summary>
        public static string faction_not_enough_money {
            get {
                return ResourceManager.GetString("faction_not_enough_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find the requested report..
        /// </summary>
        public static string faction_warning_not_found {
            get {
                return ResourceManager.GetString("faction_warning_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected report is being attended..
        /// </summary>
        public static string faction_warning_taken {
            get {
                return ResourceManager.GetString("faction_warning_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reeled too early..
        /// </summary>
        public static string fishing_canceled {
            get {
                return ResourceManager.GetString("fishing_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fish has escaped from the hook..
        /// </summary>
        public static string fishing_failed {
            get {
                return ResourceManager.GetString("fishing_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t collect garbage from the vehicle..
        /// </summary>
        public static string garbage_in_vehicle {
            get {
                return ResourceManager.GetString("garbage_in_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already wearing a pair of glasses..
        /// </summary>
        public static string glasses_equiped {
            get {
                return ResourceManager.GetString("glasses_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need at least {0}$ to change your look..
        /// </summary>
        public static string haircut_money {
            get {
                return ResourceManager.GetString("haircut_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already wearing a hat..
        /// </summary>
        public static string hat_equiped {
            get {
                return ResourceManager.GetString("hat_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can offer a service to yourself..
        /// </summary>
        public static string hooker_offered_himself {
            get {
                return ResourceManager.GetString("hooker_offered_himself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This house is already rentable..
        /// </summary>
        public static string house_already_rentable {
            get {
                return ResourceManager.GetString("house_already_rentable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interior value must be between 0 and {0}..
        /// </summary>
        public static string house_interior_modify {
            get {
                return ResourceManager.GetString("house_interior_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This house is locked..
        /// </summary>
        public static string house_locked {
            get {
                return ResourceManager.GetString("house_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need at least ${0} in your bank account to purchase this house..
        /// </summary>
        public static string house_no_money {
            get {
                return ResourceManager.GetString("house_no_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This house is not for sale..
        /// </summary>
        public static string house_not_buyable {
            get {
                return ResourceManager.GetString("house_not_buyable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any house with that identifier..
        /// </summary>
        public static string house_not_exists {
            get {
                return ResourceManager.GetString("house_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the required money to buy this house in your bank account..
        /// </summary>
        public static string house_not_money {
            get {
                return ResourceManager.GetString("house_not_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This house is not rentable..
        /// </summary>
        public static string house_not_rentable {
            get {
                return ResourceManager.GetString("house_not_rentable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t sell the house as it has people registered as living there..
        /// </summary>
        public static string house_occupied {
            get {
                return ResourceManager.GetString("house_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price of the house must be greater than 0$..
        /// </summary>
        public static string house_price_modify {
            get {
                return ResourceManager.GetString("house_price_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This house&apos;s rental price must be greater than 0$..
        /// </summary>
        public static string house_rental_modify {
            get {
                return ResourceManager.GetString("house_rental_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s been an error selling the house, check if it&apos;s still yours..
        /// </summary>
        public static string house_sell_generic {
            get {
                return ResourceManager.GetString("house_sell_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state of this house must be between 0 and 2..
        /// </summary>
        public static string house_status_modify {
            get {
                return ResourceManager.GetString("house_status_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any consumable in your hand..
        /// </summary>
        public static string item_not_consumable {
            get {
                return ResourceManager.GetString("item_not_consumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your delivered has been canceled for leaving your job vehicle..
        /// </summary>
        public static string job_vehicle_abandoned {
            get {
                return ResourceManager.GetString("job_vehicle_abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any item in your left hand..
        /// </summary>
        public static string left_hand_empty {
            get {
                return ResourceManager.GetString("left_hand_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have an item in your left hand..
        /// </summary>
        public static string left_hand_occupied {
            get {
                return ResourceManager.GetString("left_hand_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You failed the practical exam..
        /// </summary>
        public static string license_drive_failed {
            get {
                return ResourceManager.GetString("license_drive_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You failed the theoric exam..
        /// </summary>
        public static string license_exam_failed {
            get {
                return ResourceManager.GetString("license_exam_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You failed the exam for not returning to your vehicle..
        /// </summary>
        public static string license_failed_not_in_vehicle {
            get {
                return ResourceManager.GetString("license_failed_not_in_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your blood level is to low to be drawn..
        /// </summary>
        public static string low_blood {
            get {
                return ResourceManager.GetString("low_blood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already wearing a mask..
        /// </summary>
        public static string mask_equiped {
            get {
                return ResourceManager.GetString("mask_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money amount has to be positive..
        /// </summary>
        public static string money_amount_positive {
            get {
                return ResourceManager.GetString("money_amount_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t use private messages with staff members..
        /// </summary>
        public static string mps_only_admin {
            get {
                return ResourceManager.GetString("mps_only_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} got a negative result..
        /// </summary>
        public static string negative_result {
            get {
                return ResourceManager.GetString("negative_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t purchased any accessory..
        /// </summary>
        public static string no_accessory_bought {
            get {
                return ResourceManager.GetString("no_accessory_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not wearing any accessory..
        /// </summary>
        public static string no_accessory_equiped {
            get {
                return ResourceManager.GetString("no_accessory_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no staff members online, try again in a while..
        /// </summary>
        public static string no_admins_on_duty_atm {
            get {
                return ResourceManager.GetString("no_admins_on_duty_atm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t purchased any bag..
        /// </summary>
        public static string no_bag_bought {
            get {
                return ResourceManager.GetString("no_bag_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not wearing any bag..
        /// </summary>
        public static string no_bag_equiped {
            get {
                return ResourceManager.GetString("no_bag_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no blood units remaining..
        /// </summary>
        public static string no_blood_left {
            get {
                return ResourceManager.GetString("no_blood_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t select any character..
        /// </summary>
        public static string no_character_selected {
            get {
                return ResourceManager.GetString("no_character_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no clothes in the wardrobe..
        /// </summary>
        public static string no_clothes_in_wardrobe {
            get {
                return ResourceManager.GetString("no_clothes_in_wardrobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t purchased any earrings..
        /// </summary>
        public static string no_ear_bought {
            get {
                return ResourceManager.GetString("no_ear_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not wearing any earrings..
        /// </summary>
        public static string no_ear_equiped {
            get {
                return ResourceManager.GetString("no_ear_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any fish to sell..
        /// </summary>
        public static string no_fish_sellable {
            get {
                return ResourceManager.GetString("no_fish_sellable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have a fishing rod in your right hand..
        /// </summary>
        public static string no_fishing_rod {
            get {
                return ResourceManager.GetString("no_fishing_rod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t purchased any glasses..
        /// </summary>
        public static string no_glasses_bought {
            get {
                return ResourceManager.GetString("no_glasses_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not wearing any glasses..
        /// </summary>
        public static string no_glasses_equiped {
            get {
                return ResourceManager.GetString("no_glasses_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t purchased any hat..
        /// </summary>
        public static string no_hat_bought {
            get {
                return ResourceManager.GetString("no_hat_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not wearing any hat..
        /// </summary>
        public static string no_hat_equiped {
            get {
                return ResourceManager.GetString("no_hat_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any item in your inventory..
        /// </summary>
        public static string no_items_inventory {
            get {
                return ResourceManager.GetString("no_items_inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any item near..
        /// </summary>
        public static string no_items_near {
            get {
                return ResourceManager.GetString("no_items_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This vehicle&apos;s trunk is empty..
        /// </summary>
        public static string no_items_trunk {
            get {
                return ResourceManager.GetString("no_items_trunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t purchased any mask..
        /// </summary>
        public static string no_mask_bought {
            get {
                return ResourceManager.GetString("no_mask_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not wearing any mask..
        /// </summary>
        public static string no_mask_equiped {
            get {
                return ResourceManager.GetString("no_mask_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no police control saved..
        /// </summary>
        public static string no_police_controls {
            get {
                return ResourceManager.GetString("no_police_controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody offered you to repaint your vehicle..
        /// </summary>
        public static string no_repaint_offered {
            get {
                return ResourceManager.GetString("no_repaint_offered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody offered you a repairment..
        /// </summary>
        public static string no_repair_offered {
            get {
                return ResourceManager.GetString("no_repair_offered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody offered you a sexual service..
        /// </summary>
        public static string no_service_offered {
            get {
                return ResourceManager.GetString("no_service_offered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody is driving this taxi..
        /// </summary>
        public static string no_taxi_driver {
            get {
                return ResourceManager.GetString("no_taxi_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any phone in your hand..
        /// </summary>
        public static string no_telephone_hand {
            get {
                return ResourceManager.GetString("no_telephone_hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any vehicle near you..
        /// </summary>
        public static string no_vehicles_near {
            get {
                return ResourceManager.GetString("no_vehicles_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any relay equipment in your hand..
        /// </summary>
        public static string no_walkie_in_hand {
            get {
                return ResourceManager.GetString("no_walkie_in_hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have this vehicle&apos;s keys..
        /// </summary>
        public static string not_car_keys {
            get {
                return ResourceManager.GetString("not_car_keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t take any order..
        /// </summary>
        public static string not_delivering_order {
            get {
                return ResourceManager.GetString("not_delivering_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not an emergency vehicle..
        /// </summary>
        public static string not_emergency_vehicle {
            get {
                return ResourceManager.GetString("not_emergency_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not fastfood deliverer..
        /// </summary>
        public static string not_fastfood {
            get {
                return ResourceManager.GetString("not_fastfood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This vehicle isn&apos;t a fishing boat..
        /// </summary>
        public static string not_fishing_boat {
            get {
                return ResourceManager.GetString("not_fishing_boat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in a fishing store..
        /// </summary>
        public static string not_fishing_business {
            get {
                return ResourceManager.GetString("not_fishing_business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in a fishing area..
        /// </summary>
        public static string not_fishing_zone {
            get {
                return ResourceManager.GetString("not_fishing_zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in any gas station..
        /// </summary>
        public static string not_fuel_station_near {
            get {
                return ResourceManager.GetString("not_fuel_station_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any garbage bag near..
        /// </summary>
        public static string not_garbage_near {
            get {
                return ResourceManager.GetString("not_garbage_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not a hooker..
        /// </summary>
        public static string not_hooker {
            get {
                return ResourceManager.GetString("not_hooker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in the door of any house or business..
        /// </summary>
        public static string not_house_business {
            get {
                return ResourceManager.GetString("not_house_business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no house near you..
        /// </summary>
        public static string not_house_near {
            get {
                return ResourceManager.GetString("not_house_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not doing the car practical exam..
        /// </summary>
        public static string not_in_car_practice {
            get {
                return ResourceManager.GetString("not_in_car_practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in any cat dealer..
        /// </summary>
        public static string not_in_carshop {
            get {
                return ResourceManager.GetString("not_in_carshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not close to the house&apos;s door..
        /// </summary>
        public static string not_in_house_door {
            get {
                return ResourceManager.GetString("not_in_house_door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in any workshop..
        /// </summary>
        public static string not_in_mechanic_workshop {
            get {
                return ResourceManager.GetString("not_in_mechanic_workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in a pawn shop..
        /// </summary>
        public static string not_in_pawn_show {
            get {
                return ResourceManager.GetString("not_in_pawn_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in any job route..
        /// </summary>
        public static string not_in_route {
            get {
                return ResourceManager.GetString("not_in_route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t inside any vehicle..
        /// </summary>
        public static string not_in_vehicle {
            get {
                return ResourceManager.GetString("not_in_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in the same faction this vehicle is..
        /// </summary>
        public static string not_in_vehicle_faction {
            get {
                return ResourceManager.GetString("not_in_vehicle_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the required job to drive this vehicle..
        /// </summary>
        public static string not_in_vehicle_job {
            get {
                return ResourceManager.GetString("not_in_vehicle_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be into a vehicle..
        /// </summary>
        public static string not_in_vehicle_type_car {
            get {
                return ResourceManager.GetString("not_in_vehicle_type_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in the correct work place..
        /// </summary>
        public static string not_in_work_place {
            get {
                return ResourceManager.GetString("not_in_work_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target player isn&apos;t being interviewed..
        /// </summary>
        public static string not_on_air {
            get {
                return ResourceManager.GetString("not_on_air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t own any radio channel..
        /// </summary>
        public static string not_owned_channel {
            get {
                return ResourceManager.GetString("not_owned_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t park your vehicle here..
        /// </summary>
        public static string not_parking_allowed {
            get {
                return ResourceManager.GetString("not_parking_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in any parking..
        /// </summary>
        public static string not_parking_near {
            get {
                return ResourceManager.GetString("not_parking_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in a phone call..
        /// </summary>
        public static string not_phone_talking {
            get {
                return ResourceManager.GetString("not_phone_talking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not the chief from the police department..
        /// </summary>
        public static string not_police_chief {
            get {
                return ResourceManager.GetString("not_police_chief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any house rented..
        /// </summary>
        public static string not_rented_house {
            get {
                return ResourceManager.GetString("not_rented_house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need {0} products in order to do that..
        /// </summary>
        public static string not_required_products {
            get {
                return ResourceManager.GetString("not_required_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in the scrapyard..
        /// </summary>
        public static string not_scrapyard_near {
            get {
                return ResourceManager.GetString("not_scrapyard_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in duty..
        /// </summary>
        public static string not_service {
            get {
                return ResourceManager.GetString("not_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not spectating any player..
        /// </summary>
        public static string not_spectating {
            get {
                return ResourceManager.GetString("not_spectating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not allowed to test this vehicle..
        /// </summary>
        public static string not_testing_vehicle {
            get {
                return ResourceManager.GetString("not_testing_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not a thief..
        /// </summary>
        public static string not_thief {
            get {
                return ResourceManager.GetString("not_thief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not a trucker..
        /// </summary>
        public static string not_trucker {
            get {
                return ResourceManager.GetString("not_trucker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in any workshop and don&apos;t have any towtruck near..
        /// </summary>
        public static string not_valid_repair_place {
            get {
                return ResourceManager.GetString("not_valid_repair_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not driving the vehicle..
        /// </summary>
        public static string not_vehicle_driving {
            get {
                return ResourceManager.GetString("not_vehicle_driving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t on passenger&apos;s seat..
        /// </summary>
        public static string not_vehicle_passenger {
            get {
                return ResourceManager.GetString("not_vehicle_passenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not your job vehicle..
        /// </summary>
        public static string not_your_job_vehicle {
            get {
                return ResourceManager.GetString("not_your_job_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target player is being interviewed already..
        /// </summary>
        public static string on_air {
            get {
                return ResourceManager.GetString("on_air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already delivering an order..
        /// </summary>
        public static string order_delivering {
            get {
                return ResourceManager.GetString("order_delivering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no order in the list to attend..
        /// </summary>
        public static string order_none {
            get {
                return ResourceManager.GetString("order_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order has already been attended..
        /// </summary>
        public static string order_taken {
            get {
                return ResourceManager.GetString("order_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client has tired of waiting his order..
        /// </summary>
        public static string order_timeout {
            get {
                return ResourceManager.GetString("order_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This parking is full..
        /// </summary>
        public static string parking_full {
            get {
                return ResourceManager.GetString("parking_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t only link a house to a garage..
        /// </summary>
        public static string parking_not_garage {
            get {
                return ResourceManager.GetString("parking_not_garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need {0}$ to get your car from the parking..
        /// </summary>
        public static string parking_not_money {
            get {
                return ResourceManager.GetString("parking_not_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target player is already in a faction..
        /// </summary>
        public static string player_already_faction {
            get {
                return ResourceManager.GetString("player_already_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already fishing..
        /// </summary>
        public static string player_already_fishing {
            get {
                return ResourceManager.GetString("player_already_fishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already hotwiring a vehicle..
        /// </summary>
        public static string player_already_hotwiring {
            get {
                return ResourceManager.GetString("player_already_hotwiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target player already has a job..
        /// </summary>
        public static string player_already_job {
            get {
                return ResourceManager.GetString("player_already_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license is still valid..
        /// </summary>
        public static string player_already_license {
            get {
                return ResourceManager.GetString("player_already_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already stealing items..
        /// </summary>
        public static string player_already_stealing {
            get {
                return ResourceManager.GetString("player_already_stealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t use the chat in the lobby..
        /// </summary>
        public static string player_cant_chat {
            get {
                return ResourceManager.GetString("player_cant_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t use any command in the lobby..
        /// </summary>
        public static string player_cant_command {
            get {
                return ResourceManager.GetString("player_cant_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t hotwire your own vehicle..
        /// </summary>
        public static string player_cant_hotwire_own_vehicle {
            get {
                return ResourceManager.GetString("player_cant_hotwire_own_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t lockpick your own vehicle..
        /// </summary>
        public static string player_cant_lockpick_own_vehicle {
            get {
                return ResourceManager.GetString("player_cant_lockpick_own_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s nothing to steal near here..
        /// </summary>
        public static string player_cant_rob {
            get {
                return ResourceManager.GetString("player_cant_rob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t break into your own house..
        /// </summary>
        public static string player_cant_rob_own_house {
            get {
                return ResourceManager.GetString("player_cant_rob_own_house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t steal into your own vehicle..
        /// </summary>
        public static string player_cant_rob_own_vehicle {
            get {
                return ResourceManager.GetString("player_cant_rob_own_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t be the target player..
        /// </summary>
        public static string player_cant_self {
            get {
                return ResourceManager.GetString("player_cant_self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re still nervous from your last robbery, you&apos;ll have to wait 1 hour..
        /// </summary>
        public static string player_cooldown_thief {
            get {
                return ResourceManager.GetString("player_cooldown_thief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t fine yourself..
        /// </summary>
        public static string player_fined_himself {
            get {
                return ResourceManager.GetString("player_fined_himself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t handcuff yourself..
        /// </summary>
        public static string player_handcuffed_himself {
            get {
                return ResourceManager.GetString("player_handcuffed_himself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have you identification card..
        /// </summary>
        public static string player_has_identification {
            get {
                return ResourceManager.GetString("player_has_identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a job..
        /// </summary>
        public static string player_has_job {
            get {
                return ResourceManager.GetString("player_has_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a medical insurance..
        /// </summary>
        public static string player_has_medical_insurance {
            get {
                return ResourceManager.GetString("player_has_medical_insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a taxi license..
        /// </summary>
        public static string player_has_taxi_license {
            get {
                return ResourceManager.GetString("player_has_taxi_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already attending a report..
        /// </summary>
        public static string player_have_faction_warning {
            get {
                return ResourceManager.GetString("player_have_faction_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a house rented..
        /// </summary>
        public static string player_house_rented {
            get {
                return ResourceManager.GetString("player_house_rented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t incriminate yourself..
        /// </summary>
        public static string player_incriminated_himself {
            get {
                return ResourceManager.GetString("player_incriminated_himself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t do this inside a vehicle..
        /// </summary>
        public static string player_inside_vehicle {
            get {
                return ResourceManager.GetString("player_inside_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t do that while dead..
        /// </summary>
        public static string player_is_dead {
            get {
                return ResourceManager.GetString("player_is_dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t spent the required time in your current job..
        /// </summary>
        public static string player_job_restriction {
            get {
                return ResourceManager.GetString("player_job_restriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can apply for this job being part of a state faction..
        /// </summary>
        public static string player_job_state_faction {
            get {
                return ResourceManager.GetString("player_job_state_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player can&apos;t have more lent vehicles..
        /// </summary>
        public static string player_keys_full {
            get {
                return ResourceManager.GetString("player_keys_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have nothing to use as a bait..
        /// </summary>
        public static string player_no_baits {
            get {
                return ResourceManager.GetString("player_no_baits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in any faction..
        /// </summary>
        public static string player_no_faction {
            get {
                return ResourceManager.GetString("player_no_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t select any fine to pay..
        /// </summary>
        public static string player_no_fines {
            get {
                return ResourceManager.GetString("player_no_fines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any jerrycan in your hand..
        /// </summary>
        public static string player_no_jerrycan {
            get {
                return ResourceManager.GetString("player_no_jerrycan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any job..
        /// </summary>
        public static string player_no_job {
            get {
                return ResourceManager.GetString("player_no_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not the owner of this business..
        /// </summary>
        public static string player_not_business_owner {
            get {
                return ResourceManager.GetString("player_not_business_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody&apos;s calling at you in this moment..
        /// </summary>
        public static string player_not_called {
            get {
                return ResourceManager.GetString("player_not_called", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to be in a car to use this animation..
        /// </summary>
        public static string player_not_car {
            get {
                return ResourceManager.GetString("player_not_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target player is not dead..
        /// </summary>
        public static string player_not_dead {
            get {
                return ResourceManager.GetString("player_not_dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in the driving school..
        /// </summary>
        public static string player_not_driving_school {
            get {
                return ResourceManager.GetString("player_not_driving_school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t part of the emergency department..
        /// </summary>
        public static string player_not_emergency_faction {
            get {
                return ResourceManager.GetString("player_not_emergency_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough money..
        /// </summary>
        public static string player_not_enough_money {
            get {
                return ResourceManager.GetString("player_not_enough_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the required rank to get ammunition neither weapons..
        /// </summary>
        public static string player_not_enough_police_rank {
            get {
                return ResourceManager.GetString("player_not_enough_police_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need {0}$ to pay your fines..
        /// </summary>
        public static string player_not_fine_money {
            get {
                return ResourceManager.GetString("player_not_fine_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not fisherman..
        /// </summary>
        public static string player_not_fisherman {
            get {
                return ResourceManager.GetString("player_not_fisherman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target player is not connected to the server..
        /// </summary>
        public static string player_not_found {
            get {
                return ResourceManager.GetString("player_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have this garage&apos;s keys..
        /// </summary>
        public static string player_not_garage_access {
            get {
                return ResourceManager.GetString("player_not_garage_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not a garbage man..
        /// </summary>
        public static string player_not_garbage {
            get {
                return ResourceManager.GetString("player_not_garbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not the owner of this house..
        /// </summary>
        public static string player_not_house_owner {
            get {
                return ResourceManager.GetString("player_not_house_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target player is not wounded..
        /// </summary>
        public static string player_not_hurt {
            get {
                return ResourceManager.GetString("player_not_hurt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need {0}$ to get your identification card..
        /// </summary>
        public static string player_not_identification_money {
            get {
                return ResourceManager.GetString("player_not_identification_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not inside any house..
        /// </summary>
        public static string player_not_in_house {
            get {
                return ResourceManager.GetString("player_not_in_house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to be in the left rear seat of the news van..
        /// </summary>
        public static string player_not_in_news_van {
            get {
                return ResourceManager.GetString("player_not_in_news_van", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to be on the back right rear seat of the van..
        /// </summary>
        public static string player_not_in_right_rear {
            get {
                return ResourceManager.GetString("player_not_in_right_rear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in the police station&apos;s lockers..
        /// </summary>
        public static string player_not_in_room_lockers {
            get {
                return ResourceManager.GetString("player_not_in_room_lockers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target player isn&apos;t in your faction..
        /// </summary>
        public static string player_not_in_same_faction {
            get {
                return ResourceManager.GetString("player_not_in_same_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in jail&apos;s entrance..
        /// </summary>
        public static string player_not_jail_area {
            get {
                return ResourceManager.GetString("player_not_jail_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not mechanic..
        /// </summary>
        public static string player_not_mechanic {
            get {
                return ResourceManager.GetString("player_not_mechanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have a medical insurance..
        /// </summary>
        public static string player_not_medical_insurance {
            get {
                return ResourceManager.GetString("player_not_medical_insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need {0}$ to get a medical insurance..
        /// </summary>
        public static string player_not_medical_insurance_money {
            get {
                return ResourceManager.GetString("player_not_medical_insurance_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t a journalist..
        /// </summary>
        public static string player_not_news_faction {
            get {
                return ResourceManager.GetString("player_not_news_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t on duty as staff..
        /// </summary>
        public static string player_not_on_admin_duty {
            get {
                return ResourceManager.GetString("player_not_on_admin_duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t on duty..
        /// </summary>
        public static string player_not_on_duty {
            get {
                return ResourceManager.GetString("player_not_on_duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to player_not_own_death.
        /// </summary>
        public static string player_not_own_death {
            get {
                return ResourceManager.GetString("player_not_own_death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t part of the police department neither emergency department..
        /// </summary>
        public static string player_not_police_emergency_faction {
            get {
                return ResourceManager.GetString("player_not_police_emergency_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t part of the police department..
        /// </summary>
        public static string player_not_police_faction {
            get {
                return ResourceManager.GetString("player_not_police_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the required money to pay the rental fee..
        /// </summary>
        public static string player_not_rent_money {
            get {
                return ResourceManager.GetString("player_not_rent_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any fishing rod and you&apos;re not in any fishing boat..
        /// </summary>
        public static string player_not_rod_boat {
            get {
                return ResourceManager.GetString("player_not_rod_boat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t part of any state faction..
        /// </summary>
        public static string player_not_state_faction {
            get {
                return ResourceManager.GetString("player_not_state_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any stolen item..
        /// </summary>
        public static string player_not_stolen_items {
            get {
                return ResourceManager.GetString("player_not_stolen_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t own any taxi driving license..
        /// </summary>
        public static string player_not_taxi_license {
            get {
                return ResourceManager.GetString("player_not_taxi_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need {0}$ to get the taxi license..
        /// </summary>
        public static string player_not_taxi_license_money {
            get {
                return ResourceManager.GetString("player_not_taxi_license_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in the center of the city..
        /// </summary>
        public static string player_not_thief_area {
            get {
                return ResourceManager.GetString("player_not_thief_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in the town hall..
        /// </summary>
        public static string player_not_townhall {
            get {
                return ResourceManager.GetString("player_not_townhall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don-t have this vehicle&apos;s keys..
        /// </summary>
        public static string player_not_veh_owner {
            get {
                return ResourceManager.GetString("player_not_veh_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player has no clothes..
        /// </summary>
        public static string player_owns_clothes {
            get {
                return ResourceManager.GetString("player_owns_clothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already refueling your vehicle..
        /// </summary>
        public static string player_refueling {
            get {
                return ResourceManager.GetString("player_refueling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t frisk yourself..
        /// </summary>
        public static string player_searched_himself {
            get {
                return ResourceManager.GetString("player_searched_himself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target player is spectating another player..
        /// </summary>
        public static string player_spectating {
            get {
                return ResourceManager.GetString("player_spectating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You left the vehicle and stopped hotwiring it..
        /// </summary>
        public static string player_stopped_hotwire {
            get {
                return ResourceManager.GetString("player_stopped_hotwire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re too far away from the target player..
        /// </summary>
        public static string player_too_far {
            get {
                return ResourceManager.GetString("player_too_far", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t own any identification card, remember that it&apos;s mandatory to be identified..
        /// </summary>
        public static string player_undocumented {
            get {
                return ResourceManager.GetString("player_undocumented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be greater than 0$..
        /// </summary>
        public static string price_positive {
            get {
                return ResourceManager.GetString("price_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not connected to any radio frequency..
        /// </summary>
        public static string radio_frequency_none {
            get {
                return ResourceManager.GetString("radio_frequency_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the required rank to dismiss members..
        /// </summary>
        public static string rank_too_low_dismiss {
            get {
                return ResourceManager.GetString("rank_too_low_dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the required rank to change members&apos; rank..
        /// </summary>
        public static string rank_too_low_rank {
            get {
                return ResourceManager.GetString("rank_too_low_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the required rank to recruit new members..
        /// </summary>
        public static string rank_too_low_recruit {
            get {
                return ResourceManager.GetString("rank_too_low_recruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any item in your right hand..
        /// </summary>
        public static string right_hand_empty {
            get {
                return ResourceManager.GetString("right_hand_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have an item in your right hand..
        /// </summary>
        public static string right_hand_occupied {
            get {
                return ResourceManager.GetString("right_hand_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave while you&apos;re stealing items..
        /// </summary>
        public static string stealing_progress {
            get {
                return ResourceManager.GetString("stealing_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target player has already an item in his right hand..
        /// </summary>
        public static string target_right_hand_not_empty {
            get {
                return ResourceManager.GetString("target_right_hand_not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a tattoo like this one..
        /// </summary>
        public static string tattoo_duplicated {
            get {
                return ResourceManager.GetString("tattoo_duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The taxi driver already has a destination point..
        /// </summary>
        public static string taxi_has_path {
            get {
                return ResourceManager.GetString("taxi_has_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t transfer money to your own account..
        /// </summary>
        public static string transfer_money_own {
            get {
                return ResourceManager.GetString("transfer_money_own", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This vehicle is already unlocked..
        /// </summary>
        public static string veh_already_unlocked {
            get {
                return ResourceManager.GetString("veh_already_unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no vehicles loaded..
        /// </summary>
        public static string vehicle_dealer_empty {
            get {
                return ResourceManager.GetString("vehicle_dealer_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This vehicle isn&apos;t drivable with your license..
        /// </summary>
        public static string vehicle_driving_not_suitable {
            get {
                return ResourceManager.GetString("vehicle_driving_not_suitable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t park this vehicle..
        /// </summary>
        public static string vehicle_faction_park {
            get {
                return ResourceManager.GetString("vehicle_faction_park", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle is being trailered..
        /// </summary>
        public static string vehicle_is_trailered {
            get {
                return ResourceManager.GetString("vehicle_is_trailered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any vehicle with that identifier..
        /// </summary>
        public static string vehicle_not_exists {
            get {
                return ResourceManager.GetString("vehicle_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This vehicle can&apos;t be locked..
        /// </summary>
        public static string vehicle_not_lockable {
            get {
                return ResourceManager.GetString("vehicle_not_lockable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This vehicle doesn&apos;t have any megaphone installed..
        /// </summary>
        public static string vehicle_not_megaphone {
            get {
                return ResourceManager.GetString("vehicle_not_megaphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle is not parked here..
        /// </summary>
        public static string vehicle_not_this_parking {
            get {
                return ResourceManager.GetString("vehicle_not_this_parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t refuel while you&apos;re into the vehicle..
        /// </summary>
        public static string vehicle_refuel_into_vehicle {
            get {
                return ResourceManager.GetString("vehicle_refuel_into_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle is being refueled..
        /// </summary>
        public static string vehicle_refueling {
            get {
                return ResourceManager.GetString("vehicle_refueling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t turn the engine on while the vehicle is being refueled..
        /// </summary>
        public static string vehicle_start_refueling {
            get {
                return ResourceManager.GetString("vehicle_start_refueling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t turn the engine on while they&apos;re unpacking the weapons..
        /// </summary>
        public static string vehicle_start_weapon_unpacking {
            get {
                return ResourceManager.GetString("vehicle_start_weapon_unpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle&apos;s tank is already full..
        /// </summary>
        public static string vehicle_tank_full {
            get {
                return ResourceManager.GetString("vehicle_tank_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle&apos;s trunk is already closed..
        /// </summary>
        public static string vehicle_trunk_closed {
            get {
                return ResourceManager.GetString("vehicle_trunk_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s already somebody interacting with this vehicle&apos;s trunk..
        /// </summary>
        public static string vehicle_trunk_in_use {
            get {
                return ResourceManager.GetString("vehicle_trunk_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle&apos;s trunk is already opened..
        /// </summary>
        public static string vehicle_trunk_opened {
            get {
                return ResourceManager.GetString("vehicle_trunk_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle is too far away from you..
        /// </summary>
        public static string wanted_vehicle_far {
            get {
                return ResourceManager.GetString("wanted_vehicle_far", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weapons event has already started..
        /// </summary>
        public static string weapon_event_on_course {
            get {
                return ResourceManager.GetString("weapon_event_on_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your weapon license has expired..
        /// </summary>
        public static string weapon_license_expired {
            get {
                return ResourceManager.GetString("weapon_license_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather value must be in 0 to 12 interval..
        /// </summary>
        public static string weather_value_invalid {
            get {
                return ResourceManager.GetString("weather_value_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no need to repair this wheel..
        /// </summary>
        public static string wheel_not_popped {
            get {
                return ResourceManager.GetString("wheel_not_popped", resourceCulture);
            }
        }
    }
}
