//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.information {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InfoRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.information.InfoRes", typeof(InfoRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can unequip complements using /complement..
        /// </summary>
        public static string about_complements {
            get {
                return ResourceManager.GetString("about_complements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked, head to the forums if you want more detailed information..
        /// </summary>
        public static string account_disabled {
            get {
                return ResourceManager.GetString("account_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be registered in https://oceanicroleplay.com/ to log into the server..
        /// </summary>
        public static string account_new {
            get {
                return ResourceManager.GetString("account_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional data:.
        /// </summary>
        public static string additional_data {
            get {
                return ResourceManager.GetString("additional_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} performed an alcohol test on you, the result is {1} mg/l on exhaled air..
        /// </summary>
        public static string alcoholimeter_receptor {
            get {
                return ResourceManager.GetString("alcoholimeter_receptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You performed an alcohol test on {0}, the result is {1} mg/l on exhaled air..
        /// </summary>
        public static string alcoholimeter_test {
            get {
                return ResourceManager.GetString("alcoholimeter_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already on air..
        /// </summary>
        public static string already_on_air {
            get {
                return ResourceManager.GetString("already_on_air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You published an announce, the cost of the service raises to 500$..
        /// </summary>
        public static string announce_published {
            get {
                return ResourceManager.GetString("announce_published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application passed..
        /// </summary>
        public static string application_passed {
            get {
                return ResourceManager.GetString("application_passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandage.
        /// </summary>
        public static string bandage {
            get {
                return ResourceManager.GetString("bandage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic data:.
        /// </summary>
        public static string basic_data {
            get {
                return ResourceManager.GetString("basic_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You drew some blood to {0}..
        /// </summary>
        public static string blood_extracted {
            get {
                return ResourceManager.GetString("blood_extracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The doctor {0} drew some of your blood..
        /// </summary>
        public static string blood_given {
            get {
                return ResourceManager.GetString("blood_given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You bought the business named {0} for ${1}..
        /// </summary>
        public static string business_buy {
            get {
                return ResourceManager.GetString("business_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You paid {0}$ for your purchase..
        /// </summary>
        public static string business_item_purchased {
            get {
                return ResourceManager.GetString("business_item_purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You locked your business..
        /// </summary>
        public static string business_locked {
            get {
                return ResourceManager.GetString("business_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You unlocked your business..
        /// </summary>
        public static string business_opened {
            get {
                return ResourceManager.GetString("business_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is calling you. Use /answer to respond and /hang when you&apos;re finished..
        /// </summary>
        public static string call_from {
            get {
                return ResourceManager.GetString("call_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You answered the call, type /hang when you&apos;re finished..
        /// </summary>
        public static string call_received {
            get {
                return ResourceManager.GetString("call_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somebody answered your call, type /hang when you&apos;re finished..
        /// </summary>
        public static string call_taken {
            get {
                return ResourceManager.GetString("call_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re calling {0}..
        /// </summary>
        public static string calling {
            get {
                return ResourceManager.GetString("calling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chief {0} removed your car license..
        /// </summary>
        public static string car_license_lost {
            get {
                return ResourceManager.GetString("car_license_lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car: Not available..
        /// </summary>
        public static string car_license_not_available {
            get {
                return ResourceManager.GetString("car_license_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car: {0} points..
        /// </summary>
        public static string car_license_points {
            get {
                return ResourceManager.GetString("car_license_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car: Practical pending..
        /// </summary>
        public static string car_license_practical_pending {
            get {
                return ResourceManager.GetString("car_license_practical_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You removed the car license from {0}..
        /// </summary>
        public static string car_license_removed {
            get {
                return ResourceManager.GetString("car_license_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a new incoming call..
        /// </summary>
        public static string central_call {
            get {
                return ResourceManager.GetString("central_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been connected to the channel {0}..
        /// </summary>
        public static string channel_connected {
            get {
                return ResourceManager.GetString("channel_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have created the radio frequency channel {0}..
        /// </summary>
        public static string channel_created {
            get {
                return ResourceManager.GetString("channel_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You deleted the radio frequency channel..
        /// </summary>
        public static string channel_deleted {
            get {
                return ResourceManager.GetString("channel_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been disconnected from the radio frequency channel..
        /// </summary>
        public static string channel_disconnected {
            get {
                return ResourceManager.GetString("channel_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You updated channel&apos;s password..
        /// </summary>
        public static string channel_updated {
            get {
                return ResourceManager.GetString("channel_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} checks the plate of the {1}..
        /// </summary>
        public static string check_vehicle_plate {
            get {
                return ResourceManager.GetString("check_vehicle_plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands for {0}.
        /// </summary>
        public static string commands_from {
            get {
                return ResourceManager.GetString("commands_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You added &apos;{0}&apos; with number {1} to your contacts list..
        /// </summary>
        public static string contact_created {
            get {
                return ResourceManager.GetString("contact_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You deleted &apos;{0}&apos; with number {1} from your contacts list..
        /// </summary>
        public static string contact_deleted {
            get {
                return ResourceManager.GetString("contact_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You modified a contact in your contacts list..
        /// </summary>
        public static string contact_modified {
            get {
                return ResourceManager.GetString("contact_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper.
        /// </summary>
        public static string copper {
            get {
                return ResourceManager.GetString("copper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You hancuffed {0}..
        /// </summary>
        public static string cuffed {
            get {
                return ResourceManager.GetString("cuffed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The officer {0} has handcuffed you..
        /// </summary>
        public static string cuffed_by {
            get {
                return ResourceManager.GetString("cuffed_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for the emergency department to reach your position..
        /// </summary>
        public static string death_time_not_passed {
            get {
                return ResourceManager.GetString("death_time_not_passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You delivered the order, go back to your job in order to get paid..
        /// </summary>
        public static string deliver_completed {
            get {
                return ResourceManager.GetString("deliver_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve got {0} seconds to deliver the order. You can cancel it using /cancel..
        /// </summary>
        public static string deliver_order {
            get {
                return ResourceManager.GetString("deliver_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You canceled the delivery order, now you can take a new one..
        /// </summary>
        public static string deliverer_order_canceled {
            get {
                return ResourceManager.GetString("deliverer_order_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A report has been sent to the emergency department..
        /// </summary>
        public static string emergency_warn {
            get {
                return ResourceManager.GetString("emergency_warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a new emergency report. Use /attend {0}..
        /// </summary>
        public static string emergency_warning {
            get {
                return ResourceManager.GetString("emergency_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get into a motorcycle from the driving school to start the license exam. Don&apos;t forget to keep the speed under 100 km/h..
        /// </summary>
        public static string enter_license_bike_vehicle {
            get {
                return ResourceManager.GetString("enter_license_bike_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get into a car from the driving school to start the license exam. Don&apos;t forget to keep the speed under 100 km/h..
        /// </summary>
        public static string enter_license_car_vehicle {
            get {
                return ResourceManager.GetString("enter_license_car_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You took ammunition for each of your weapons..
        /// </summary>
        public static string equip_ammo_received {
            get {
                return ResourceManager.GetString("equip_ammo_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You took your basic equipment..
        /// </summary>
        public static string equip_basic_received {
            get {
                return ResourceManager.GetString("equip_basic_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You took a weapon..
        /// </summary>
        public static string equip_weap_received {
            get {
                return ResourceManager.GetString("equip_weap_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kicked you out of the faction..
        /// </summary>
        public static string faction_dismissed {
            get {
                return ResourceManager.GetString("faction_dismissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed your rank to {1}..
        /// </summary>
        public static string faction_rank_changed {
            get {
                return ResourceManager.GetString("faction_rank_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were recuited in the &apos;{0}&apos; faction..
        /// </summary>
        public static string faction_recruited {
            get {
                return ResourceManager.GetString("faction_recruited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report you were attending has been canceled..
        /// </summary>
        public static string faction_warn_canceled {
            get {
                return ResourceManager.GetString("faction_warn_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You removed the report with identifier {0}..
        /// </summary>
        public static string faction_warning_deleted {
            get {
                return ResourceManager.GetString("faction_warning_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You attended the report and the position has been marked in your GPS..
        /// </summary>
        public static string faction_warning_taken {
            get {
                return ResourceManager.GetString("faction_warning_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You set a fine to {0}..
        /// </summary>
        public static string fine_given {
            get {
                return ResourceManager.GetString("fine_given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The officer {0} has set a fine on you..
        /// </summary>
        public static string fine_received {
            get {
                return ResourceManager.GetString("fine_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call has ended..
        /// </summary>
        public static string finished_call {
            get {
                return ResourceManager.GetString("finished_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The captured fish&apos;s weight is {0} grams..
        /// </summary>
        public static string fished_weight {
            get {
                return ResourceManager.GetString("fished_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won {0}$ selling your fishes..
        /// </summary>
        public static string fishing_won {
            get {
                return ResourceManager.GetString("fishing_won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the &apos;no gloves&apos; option in torso section in order to correctly show your upper clothes.
        /// </summary>
        public static string for_avoid_clipping1 {
            get {
                return ResourceManager.GetString("for_avoid_clipping1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and to avoid texture clipping..
        /// </summary>
        public static string for_avoid_clipping2 {
            get {
                return ResourceManager.GetString("for_avoid_clipping2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You picked up the garbage bag..
        /// </summary>
        public static string garbage_collected {
            get {
                return ResourceManager.GetString("garbage_collected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won {0}$ for successfully completing the route..
        /// </summary>
        public static string garbage_earnings {
            get {
                return ResourceManager.GetString("garbage_earnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You fished worthless garbage..
        /// </summary>
        public static string garbage_fished {
            get {
                return ResourceManager.GetString("garbage_fished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You canceled the garbage collecting route..
        /// </summary>
        public static string garbage_route_canceled {
            get {
                return ResourceManager.GetString("garbage_route_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string gold {
            get {
                return ResourceManager.GetString("gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth {0}%.
        /// </summary>
        public static string growth {
            get {
                return ResourceManager.GetString("growth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You paid {0}$ for your new look..
        /// </summary>
        public static string haircut_purchased {
            get {
                return ResourceManager.GetString("haircut_purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You closed the vehicle&apos;s hood..
        /// </summary>
        public static string hood_closed {
            get {
                return ResourceManager.GetString("hood_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You opened the vehicle&apos;s hood..
        /// </summary>
        public static string hood_opened {
            get {
                return ResourceManager.GetString("hood_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You canceled the service..
        /// </summary>
        public static string hooker_service_canceled {
            get {
                return ResourceManager.GetString("hooker_service_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You started hotwiring the vehicle..
        /// </summary>
        public static string hotwire_started {
            get {
                return ResourceManager.GetString("hotwire_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bought your house for {1}$..
        /// </summary>
        public static string house_bought {
            get {
                return ResourceManager.GetString("house_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You bought the house named {0} for {1}$..
        /// </summary>
        public static string house_buy {
            get {
                return ResourceManager.GetString("house_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You bought {0}&apos;s house for {1}$..
        /// </summary>
        public static string house_buyto {
            get {
                return ResourceManager.GetString("house_buyto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You locked your house..
        /// </summary>
        public static string house_locked {
            get {
                return ResourceManager.GetString("house_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You unlocked your house..
        /// </summary>
        public static string house_opened {
            get {
                return ResourceManager.GetString("house_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You rented the house {0} paying a fee of {1}$..
        /// </summary>
        public static string house_rent {
            get {
                return ResourceManager.GetString("house_rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You removed house&apos;s rental price..
        /// </summary>
        public static string house_rent_cancel {
            get {
                return ResourceManager.GetString("house_rent_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You canceled your rent for the house {0}..
        /// </summary>
        public static string house_rent_stop {
            get {
                return ResourceManager.GetString("house_rent_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re selling you house to {0} for {1}$.
        /// </summary>
        public static string house_sell {
            get {
                return ResourceManager.GetString("house_sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use /accept house to sell your house for ${0}.
        /// </summary>
        public static string house_sell_state {
            get {
                return ResourceManager.GetString("house_sell_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is trying to sell you his house for {1}$. Use /accept house to buy it..
        /// </summary>
        public static string house_sold {
            get {
                return ResourceManager.GetString("house_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You set a rental price of {0}$..
        /// </summary>
        public static string house_state_rent {
            get {
                return ResourceManager.GetString("house_state_rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered a vehicle, press K to toggle the engine on or off..
        /// </summary>
        public static string how_to_start_engine {
            get {
                return ResourceManager.GetString("how_to_start_engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows his identification card to {0}..
        /// </summary>
        public static string identification_show {
            get {
                return ResourceManager.GetString("identification_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re receiving an incoming call. Use /answer and /hang when you are finished..
        /// </summary>
        public static string incoming_call {
            get {
                return ResourceManager.GetString("incoming_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows his medical insurance to {0}..
        /// </summary>
        public static string insurance_show {
            get {
                return ResourceManager.GetString("insurance_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron.
        /// </summary>
        public static string iron {
            get {
                return ResourceManager.GetString("iron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You gave your {0} to {1}..
        /// </summary>
        public static string item_given {
            get {
                return ResourceManager.GetString("item_given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gave you his {1}..
        /// </summary>
        public static string item_received {
            get {
                return ResourceManager.GetString("item_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new job. Use /duty to start working..
        /// </summary>
        public static string job_accepted {
            get {
                return ResourceManager.GetString("job_accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job data:.
        /// </summary>
        public static string job_data {
            get {
                return ResourceManager.GetString("job_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You left your current job..
        /// </summary>
        public static string job_left {
            get {
                return ResourceManager.GetString("job_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get back into the vehicle within {0} seconds or you&apos;ll get a penalty..
        /// </summary>
        public static string job_vehicle_left {
            get {
                return ResourceManager.GetString("job_vehicle_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won {0}$ for the successful job..
        /// </summary>
        public static string job_won {
            get {
                return ResourceManager.GetString("job_won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You paid {0}$ for the lawyer..
        /// </summary>
        public static string law_service_paid {
            get {
                return ResourceManager.GetString("law_service_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client paid you {0}$ for the service..
        /// </summary>
        public static string law_service_received {
            get {
                return ResourceManager.GetString("law_service_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You offered {0} lawyer services for {1}$, wait for the person to accept..
        /// </summary>
        public static string lawyer_service_offer {
            get {
                return ResourceManager.GetString("lawyer_service_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} offered you lawyer services for {1}$, type /accept service to make a deal..
        /// </summary>
        public static string lawyer_service_receive {
            get {
                return ResourceManager.GetString("lawyer_service_receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead.
        /// </summary>
        public static string lead {
            get {
                return ResourceManager.GetString("lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player licenses:.
        /// </summary>
        public static string license_list {
            get {
                return ResourceManager.GetString("license_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get back into the vehicle within {0} seconds or you&apos;ll fail the license exam..
        /// </summary>
        public static string license_vehicle_exit {
            get {
                return ResourceManager.GetString("license_vehicle_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows his licenses to {0}..
        /// </summary>
        public static string licenses_show {
            get {
                return ResourceManager.GetString("licenses_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All telephone lines are busy at this moment..
        /// </summary>
        public static string line_occupied {
            get {
                return ResourceManager.GetString("line_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wants to repaint your vehicle for {1}$. Use /accept repaint to accept it..
        /// </summary>
        public static string mechanic_repaint_accept {
            get {
                return ResourceManager.GetString("mechanic_repaint_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sent a repaint offer to {0} for {1}$, wait for him to accept it..
        /// </summary>
        public static string mechanic_repaint_offer {
            get {
                return ResourceManager.GetString("mechanic_repaint_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wants to repair your vehicle for {1}$. Use /accept repair to accept it..
        /// </summary>
        public static string mechanic_repair_accept {
            get {
                return ResourceManager.GetString("mechanic_repair_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sent a repair offer to {0} for {1}$, wait for him to accept it..
        /// </summary>
        public static string mechanic_repair_offer {
            get {
                return ResourceManager.GetString("mechanic_repair_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You healed {0}..
        /// </summary>
        public static string medic_healed_player {
            get {
                return ResourceManager.GetString("medic_healed_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reanimated {1}..
        /// </summary>
        public static string medic_reanimated {
            get {
                return ResourceManager.GetString("medic_reanimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medkit.
        /// </summary>
        public static string medkit {
            get {
                return ResourceManager.GetString("medkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chief {0} removed your motorcycle license..
        /// </summary>
        public static string moto_license_lost {
            get {
                return ResourceManager.GetString("moto_license_lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You removed the motorcycle license from {0}..
        /// </summary>
        public static string moto_license_removed {
            get {
                return ResourceManager.GetString("moto_license_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcycle: Not available..
        /// </summary>
        public static string motorcycle_license_not_available {
            get {
                return ResourceManager.GetString("motorcycle_license_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcycle: {0} points..
        /// </summary>
        public static string motorcycle_license_points {
            get {
                return ResourceManager.GetString("motorcycle_license_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcycle: Practical pending..
        /// </summary>
        public static string motorcycle_license_practical_pending {
            get {
                return ResourceManager.GetString("motorcycle_license_practical_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You finished the interview..
        /// </summary>
        public static string on_air_canceled {
            get {
                return ResourceManager.GetString("on_air_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You offered {0} oral sex for {1}$, wait for them to accept..
        /// </summary>
        public static string oral_service_offer {
            get {
                return ResourceManager.GetString("oral_service_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} offered you oral sex for {1}$, type /accept service to start with it..
        /// </summary>
        public static string oral_service_receive {
            get {
                return ResourceManager.GetString("oral_service_receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The emergency department has received the report and it&apos;s on its way..
        /// </summary>
        public static string paramedic_on_way {
            get {
                return ResourceManager.GetString("paramedic_on_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You parked your vehicle, there&apos;s a {0}$ fee per hour spent..
        /// </summary>
        public static string parking_cost {
            get {
                return ResourceManager.GetString("parking_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This parking is empty..
        /// </summary>
        public static string parking_empty {
            get {
                return ResourceManager.GetString("parking_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movements details of the account&apos;s balance.
        /// </summary>
        public static string payday_title {
            get {
                return ResourceManager.GetString("payday_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You rejected the payment..
        /// </summary>
        public static string payment_canceled {
            get {
                return ResourceManager.GetString("payment_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You offered a {0}$ payment to {1}..
        /// </summary>
        public static string payment_offer {
            get {
                return ResourceManager.GetString("payment_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} offered you a {1}$ payment. Type /accept money or /cancel money..
        /// </summary>
        public static string payment_received {
            get {
                return ResourceManager.GetString("payment_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone you&apos;re calling at is not responding..
        /// </summary>
        public static string phone_disconnected {
            get {
                return ResourceManager.GetString("phone_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current phone number is: {0}..
        /// </summary>
        public static string phone_number {
            get {
                return ResourceManager.GetString("phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have collected {0} leaves of weed..
        /// </summary>
        public static string plant_collected {
            get {
                return ResourceManager.GetString("plant_collected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The guest has accepted the interview. You can use /n to speak on air with him..
        /// </summary>
        public static string player_accept_on_air {
            get {
                return ResourceManager.GetString("player_accept_on_air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not on duty as an Admin anymore..
        /// </summary>
        public static string player_admin_free_time {
            get {
                return ResourceManager.GetString("player_admin_free_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re now on duty as an Admin..
        /// </summary>
        public static string player_admin_on_duty {
            get {
                return ResourceManager.GetString("player_admin_on_duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sold Bronze bars for {0}$.
        /// </summary>
        public static string player_bronzebar_sold {
            get {
                return ResourceManager.GetString("player_bronzebar_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the emergency service is not still on its way, you can use /die to be teleported to the hospital..
        /// </summary>
        public static string player_can_die {
            get {
                return ResourceManager.GetString("player_can_die", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sold Cocain for {0}$.
        /// </summary>
        public static string player_cocain_sold {
            get {
                return ResourceManager.GetString("player_cocain_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sold Copper bars for {0}$.
        /// </summary>
        public static string player_copperbar_sold {
            get {
                return ResourceManager.GetString("player_copperbar_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disconnected ({1}).
        /// </summary>
        public static string player_disconnected {
            get {
                return ResourceManager.GetString("player_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You kicked {0} out of the faction..
        /// </summary>
        public static string player_dismissed {
            get {
                return ResourceManager.GetString("player_dismissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You paid {0}$ for your fines..
        /// </summary>
        public static string player_fines_paid {
            get {
                return ResourceManager.GetString("player_fines_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You casted your fishing rod..
        /// </summary>
        public static string player_fishing_rod_thrown {
            get {
                return ResourceManager.GetString("player_fishing_rod_thrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your workshift has come to its end..
        /// </summary>
        public static string player_free_time {
            get {
                return ResourceManager.GetString("player_free_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} frisks {1}..
        /// </summary>
        public static string player_frisk {
            get {
                return ResourceManager.GetString("player_frisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sold Gold bars for {0}$.
        /// </summary>
        public static string player_goldbar_sold {
            get {
                return ResourceManager.GetString("player_goldbar_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You paid {0}$ for the identification card..
        /// </summary>
        public static string player_has_indentification {
            get {
                return ResourceManager.GetString("player_has_indentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You paid {0}$ for the medical insurance..
        /// </summary>
        public static string player_has_medical_insurance {
            get {
                return ResourceManager.GetString("player_has_medical_insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You paid {0}$ for the taxi license..
        /// </summary>
        public static string player_has_taxi_license {
            get {
                return ResourceManager.GetString("player_has_taxi_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor {0} healed your wounds..
        /// </summary>
        public static string player_healed_medic {
            get {
                return ResourceManager.GetString("player_healed_medic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You consumed your {0}..
        /// </summary>
        public static string player_inventory_consume {
            get {
                return ResourceManager.GetString("player_inventory_consume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dropped your {0}..
        /// </summary>
        public static string player_inventory_drop {
            get {
                return ResourceManager.GetString("player_inventory_drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You withdrew your {0} from the inventory..
        /// </summary>
        public static string player_inventory_equip {
            get {
                return ResourceManager.GetString("player_inventory_equip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You opened your {0}..
        /// </summary>
        public static string player_inventory_open {
            get {
                return ResourceManager.GetString("player_inventory_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sold Iron bars for {0}$.
        /// </summary>
        public static string player_ironbar_sold {
            get {
                return ResourceManager.GetString("player_ironbar_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sold Lead bars for {0}$.
        /// </summary>
        public static string player_leadbar_sold {
            get {
                return ResourceManager.GetString("player_leadbar_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You gained 1 Exp for lockpicking..
        /// </summary>
        public static string player_lockpicked_exp {
            get {
                return ResourceManager.GetString("player_lockpicked_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any fine pending to be paid..
        /// </summary>
        public static string player_no_fines {
            get {
                return ResourceManager.GetString("player_no_fines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interview has been stopped by the journalist..
        /// </summary>
        public static string player_on_air_cutted {
            get {
                return ResourceManager.GetString("player_on_air_cutted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re now on duty..
        /// </summary>
        public static string player_on_duty {
            get {
                return ResourceManager.GetString("player_on_duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gave you {1}$..
        /// </summary>
        public static string player_paid {
            get {
                return ResourceManager.GetString("player_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received {0}$ for pawning some items..
        /// </summary>
        public static string player_pawned_items {
            get {
                return ResourceManager.GetString("player_pawned_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new phone number is: {0}..
        /// </summary>
        public static string player_phone {
            get {
                return ResourceManager.GetString("player_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You picked up an item from the ground..
        /// </summary>
        public static string player_picked_item {
            get {
                return ResourceManager.GetString("player_picked_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You changed {0}&apos;s rank to {1}..
        /// </summary>
        public static string player_rank_changed {
            get {
                return ResourceManager.GetString("player_rank_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reanimated {0}..
        /// </summary>
        public static string player_reanimated {
            get {
                return ResourceManager.GetString("player_reanimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You recruited {0} into your faction..
        /// </summary>
        public static string player_recruited {
            get {
                return ResourceManager.GetString("player_recruited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve requested reinforces in your position..
        /// </summary>
        public static string player_reinforces_asked {
            get {
                return ResourceManager.GetString("player_reinforces_asked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve canceled the reinforces request..
        /// </summary>
        public static string player_reinforces_canceled {
            get {
                return ResourceManager.GetString("player_reinforces_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to rest before starting a new robbery..
        /// </summary>
        public static string player_rob_pressure {
            get {
                return ResourceManager.GetString("player_rob_pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You stole {0} items..
        /// </summary>
        public static string player_robbed {
            get {
                return ResourceManager.GetString("player_robbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can test this vehicle freely, when you are finished get it back..
        /// </summary>
        public static string player_test_vehicle {
            get {
                return ResourceManager.GetString("player_test_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gets his phone out and types something on it..
        /// </summary>
        public static string player_texting {
            get {
                return ResourceManager.GetString("player_texting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sold Tin bars for {0}$.
        /// </summary>
        public static string player_tinbar_sold {
            get {
                return ResourceManager.GetString("player_tinbar_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time&apos;s over, you&apos;re no longer in jail..
        /// </summary>
        public static string player_unjailed {
            get {
                return ResourceManager.GetString("player_unjailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for the partner to get into the truck..
        /// </summary>
        public static string player_waiting_partner {
            get {
                return ResourceManager.GetString("player_waiting_partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You removed all the elements in the police control..
        /// </summary>
        public static string police_control_cleared {
            get {
                return ResourceManager.GetString("police_control_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The officer {0} has requised your stolen items..
        /// </summary>
        public static string police_retired_items_from {
            get {
                return ResourceManager.GetString("police_retired_items_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You requised suspicious material from {0}..
        /// </summary>
        public static string police_retired_items_to {
            get {
                return ResourceManager.GetString("police_retired_items_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a new robbery report. Use /attend..
        /// </summary>
        public static string police_warning {
            get {
                return ResourceManager.GetString("police_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You gave a {0}$ prize to {1}..
        /// </summary>
        public static string prize_given {
            get {
                return ResourceManager.GetString("prize_given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gave you a {1}$ prize. Reason: {2}..
        /// </summary>
        public static string prize_received {
            get {
                return ResourceManager.GetString("prize_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You bought {0} products for {1}$..
        /// </summary>
        public static string products_bought {
            get {
                return ResourceManager.GetString("products_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties:.
        /// </summary>
        public static string properties {
            get {
                return ResourceManager.GetString("properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You canceled the repaint request..
        /// </summary>
        public static string repaint_canceled {
            get {
                return ResourceManager.GetString("repaint_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The repair will consume {0} products..
        /// </summary>
        public static string repair_price {
            get {
                return ResourceManager.GetString("repair_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You stopped interviewing the guest..
        /// </summary>
        public static string reporter_on_air_cutted {
            get {
                return ResourceManager.GetString("reporter_on_air_cutted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You canceled your route, get the vehicle back to the dump..
        /// </summary>
        public static string route_canceled {
            get {
                return ResourceManager.GetString("route_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You finished your route, get the vehicle back to the dump..
        /// </summary>
        public static string route_finished {
            get {
                return ResourceManager.GetString("route_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re now searching for valuable items..
        /// </summary>
        public static string searching_value_items {
            get {
                return ResourceManager.GetString("searching_value_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has fasten his seatbelt..
        /// </summary>
        public static string seatbelt_fasten {
            get {
                return ResourceManager.GetString("seatbelt_fasten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has unfasten his seatbelt..
        /// </summary>
        public static string seatbelt_unfasten {
            get {
                return ResourceManager.GetString("seatbelt_unfasten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You paid {0}$ for the service..
        /// </summary>
        public static string service_paid {
            get {
                return ResourceManager.GetString("service_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client paid you {0}$ for the service..
        /// </summary>
        public static string service_received {
            get {
                return ResourceManager.GetString("service_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You offered {0} sex for {1}$, wait for them to accept..
        /// </summary>
        public static string sex_service_offer {
            get {
                return ResourceManager.GetString("sex_service_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} offered you sex for {1}$, type /accept service to start with it..
        /// </summary>
        public static string sex_service_receive {
            get {
                return ResourceManager.GetString("sex_service_receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sent an SMS successfully..
        /// </summary>
        public static string sms_sent {
            get {
                return ResourceManager.GetString("sms_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You feel a bite on your rod! Reel it in..
        /// </summary>
        public static string something_baited {
            get {
                return ResourceManager.GetString("something_baited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string str {
            get {
                return ResourceManager.GetString("str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You gave {0}$ to {1}..
        /// </summary>
        public static string target_paid {
            get {
                return ResourceManager.GetString("target_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The officer {0} has requested reinforces in his position..
        /// </summary>
        public static string target_reinforces_asked {
            get {
                return ResourceManager.GetString("target_reinforces_asked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The officer {0} has canceled his reinforces request..
        /// </summary>
        public static string target_reinforces_canceled {
            get {
                return ResourceManager.GetString("target_reinforces_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You paid {0}$ for your tattoo..
        /// </summary>
        public static string tattoo_purchased {
            get {
                return ResourceManager.GetString("tattoo_purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi: Not available..
        /// </summary>
        public static string taxi_license_not_available {
            get {
                return ResourceManager.GetString("taxi_license_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi: Valid..
        /// </summary>
        public static string taxi_license_up_to_date {
            get {
                return ResourceManager.GetString("taxi_license_up_to_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer to your ticket: {0}.
        /// </summary>
        public static string ticket_answer {
            get {
                return ResourceManager.GetString("ticket_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket list:.
        /// </summary>
        public static string ticket_list {
            get {
                return ResourceManager.GetString("ticket_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are too far away from the vehicle..
        /// </summary>
        public static string too_far_veh {
            get {
                return ResourceManager.GetString("too_far_veh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You closed the vehicle&apos;s trunk..
        /// </summary>
        public static string trunk_closed {
            get {
                return ResourceManager.GetString("trunk_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to withdrew something from his vehicle&apos;s trunk..
        /// </summary>
        public static string trunk_item_withdraw {
            get {
                return ResourceManager.GetString("trunk_item_withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You opened the vehicle&apos;s trunk..
        /// </summary>
        public static string trunk_opened {
            get {
                return ResourceManager.GetString("trunk_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You placed an item into the vehicle&apos;s trunk..
        /// </summary>
        public static string trunk_stored_items {
            get {
                return ResourceManager.GetString("trunk_stored_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You withdrew something from the vehicle&apos;s trunk..
        /// </summary>
        public static string trunk_withdraw_items {
            get {
                return ResourceManager.GetString("trunk_withdraw_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need {0} products for this modification..
        /// </summary>
        public static string tunning_products {
            get {
                return ResourceManager.GetString("tunning_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You removed the handcuffs from {0}..
        /// </summary>
        public static string uncuffed {
            get {
                return ResourceManager.GetString("uncuffed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The officer {0} has removed your handcuffs..
        /// </summary>
        public static string uncuffed_by {
            get {
                return ResourceManager.GetString("uncuffed_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You paid {0}$ for having the car in this parking..
        /// </summary>
        public static string unpark_money {
            get {
                return ResourceManager.GetString("unpark_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This vehicle is already unlocked..
        /// </summary>
        public static string veh_already_unlocked {
            get {
                return ResourceManager.GetString("veh_already_unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You locked the vehicle..
        /// </summary>
        public static string veh_locked {
            get {
                return ResourceManager.GetString("veh_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You unlocked the vehicle..
        /// </summary>
        public static string veh_unlocked {
            get {
                return ResourceManager.GetString("veh_unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bought your {1} for {2}$..
        /// </summary>
        public static string vehicle_bought {
            get {
                return ResourceManager.GetString("vehicle_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You bought {0}&apos;s {1} for {2}$..
        /// </summary>
        public static string vehicle_buy {
            get {
                return ResourceManager.GetString("vehicle_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You parked the vehicle in the police depot..
        /// </summary>
        public static string vehicle_deposit_parked {
            get {
                return ResourceManager.GetString("vehicle_deposit_parked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You parked your vehicle in the garage..
        /// </summary>
        public static string vehicle_garage_parked {
            get {
                return ResourceManager.GetString("vehicle_garage_parked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lent {0} the keys of your vehicle..
        /// </summary>
        public static string vehicle_keys_given {
            get {
                return ResourceManager.GetString("vehicle_keys_given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle {0} with model {1} is owned by {2}.
        /// </summary>
        public static string vehicle_keys_info {
            get {
                return ResourceManager.GetString("vehicle_keys_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has lent you his vehicle keys..
        /// </summary>
        public static string vehicle_keys_received {
            get {
                return ResourceManager.GetString("vehicle_keys_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dropped vehicle&apos;s keys..
        /// </summary>
        public static string vehicle_keys_thrown {
            get {
                return ResourceManager.GetString("vehicle_keys_thrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle&apos;s position has been marked on your GPS..
        /// </summary>
        public static string vehicle_parked {
            get {
                return ResourceManager.GetString("vehicle_parked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve refilled your vehicle..
        /// </summary>
        public static string vehicle_refilled {
            get {
                return ResourceManager.GetString("vehicle_refilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your vehicle has been refueled..
        /// </summary>
        public static string vehicle_refueled {
            get {
                return ResourceManager.GetString("vehicle_refueled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re refueling your vehicle, wait for it to finish..
        /// </summary>
        public static string vehicle_refueling {
            get {
                return ResourceManager.GetString("vehicle_refueling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} repainted your vehicle for {1}$..
        /// </summary>
        public static string vehicle_repainted_by {
            get {
                return ResourceManager.GetString("vehicle_repainted_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You repainted {0}&apos;s vehicle for {1}$..
        /// </summary>
        public static string vehicle_repainted_to {
            get {
                return ResourceManager.GetString("vehicle_repainted_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} repaired your vehicle for {1}$..
        /// </summary>
        public static string vehicle_repaired_by {
            get {
                return ResourceManager.GetString("vehicle_repaired_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You repaired {0}&apos;s vehicle for {1}$..
        /// </summary>
        public static string vehicle_repaired_to {
            get {
                return ResourceManager.GetString("vehicle_repaired_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re selling your {0} to {1} for {2}$..
        /// </summary>
        public static string vehicle_sell {
            get {
                return ResourceManager.GetString("vehicle_sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is trying to sell you his {1} for {2}$. Use /accept vehicle to buy it..
        /// </summary>
        public static string vehicle_sold {
            get {
                return ResourceManager.GetString("vehicle_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully modified the vehicle..
        /// </summary>
        public static string vehicle_tunning {
            get {
                return ResourceManager.GetString("vehicle_tunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You turned the engine off..
        /// </summary>
        public static string vehicle_turned_off {
            get {
                return ResourceManager.GetString("vehicle_turned_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You turned the engine on..
        /// </summary>
        public static string vehicle_turned_on {
            get {
                return ResourceManager.GetString("vehicle_turned_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have taken your vehicle out..
        /// </summary>
        public static string vehicle_unparked {
            get {
                return ResourceManager.GetString("vehicle_unparked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for weapons to be unloaded from their boxes..
        /// </summary>
        public static string wait_for_weapons {
            get {
                return ResourceManager.GetString("wait_for_weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for the driver to get into the truck..
        /// </summary>
        public static string wait_garbage_driver {
            get {
                return ResourceManager.GetString("wait_garbage_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You issued a weapon license to {0}..
        /// </summary>
        public static string weapon_license_given {
            get {
                return ResourceManager.GetString("weapon_license_given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chief {0} removed your weapon license..
        /// </summary>
        public static string weapon_license_lost {
            get {
                return ResourceManager.GetString("weapon_license_lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chief {0} issued you a weapon license..
        /// </summary>
        public static string weapon_license_received {
            get {
                return ResourceManager.GetString("weapon_license_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You removed the weapon license from {0}..
        /// </summary>
        public static string weapon_license_removed {
            get {
                return ResourceManager.GetString("weapon_license_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head to the place marked in your GPS to open the boxes..
        /// </summary>
        public static string weapon_position_mark {
            get {
                return ResourceManager.GetString("weapon_position_mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some boats have been seen on the high seas..
        /// </summary>
        public static string weapon_prewarn {
            get {
                return ResourceManager.GetString("weapon_prewarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ship unloaded some material on an island to the north-east..
        /// </summary>
        public static string weapon_spawn_island {
            get {
                return ResourceManager.GetString("weapon_spawn_island", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The boxes are opened, you can take the weapons to a safe place..
        /// </summary>
        public static string weapons_unpacked {
            get {
                return ResourceManager.GetString("weapons_unpacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Weazel News journalista has offered you an interview..
        /// </summary>
        public static string wz_accept_onair {
            get {
                return ResourceManager.GetString("wz_accept_onair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You offered an interview to another player..
        /// </summary>
        public static string wz_offer_onair {
            get {
                return ResourceManager.GetString("wz_offer_onair", resourceCulture);
            }
        }
    }
}
