//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.jobs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JobRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JobRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.jobs.JobRes", typeof(JobRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string doc_0_f {
            get {
                return ResourceManager.GetString("doc_0_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string doc_0_m {
            get {
                return ResourceManager.GetString("doc_0_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison Guard.
        /// </summary>
        public static string doc_1_f {
            get {
                return ResourceManager.GetString("doc_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison Guard.
        /// </summary>
        public static string doc_1_m {
            get {
                return ResourceManager.GetString("doc_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison Guard.
        /// </summary>
        public static string doc_2_f {
            get {
                return ResourceManager.GetString("doc_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison Guard.
        /// </summary>
        public static string doc_2_m {
            get {
                return ResourceManager.GetString("doc_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison Guard.
        /// </summary>
        public static string doc_3_f {
            get {
                return ResourceManager.GetString("doc_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison Guard.
        /// </summary>
        public static string doc_3_m {
            get {
                return ResourceManager.GetString("doc_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison Guard.
        /// </summary>
        public static string doc_4_f {
            get {
                return ResourceManager.GetString("doc_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison Guard.
        /// </summary>
        public static string doc_4_m {
            get {
                return ResourceManager.GetString("doc_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison Guard.
        /// </summary>
        public static string doc_5_f {
            get {
                return ResourceManager.GetString("doc_5_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison Guard.
        /// </summary>
        public static string doc_5_m {
            get {
                return ResourceManager.GetString("doc_5_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison Guard.
        /// </summary>
        public static string doc_6_f {
            get {
                return ResourceManager.GetString("doc_6_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison Guard.
        /// </summary>
        public static string doc_6_m {
            get {
                return ResourceManager.GetString("doc_6_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison Guard.
        /// </summary>
        public static string doc_7_f {
            get {
                return ResourceManager.GetString("doc_7_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison Guard.
        /// </summary>
        public static string doc_7_m {
            get {
                return ResourceManager.GetString("doc_7_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary.
        /// </summary>
        public static string ems_1_f {
            get {
                return ResourceManager.GetString("ems_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary.
        /// </summary>
        public static string ems_1_m {
            get {
                return ResourceManager.GetString("ems_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string ems_10_f {
            get {
                return ResourceManager.GetString("ems_10_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string ems_10_m {
            get {
                return ResourceManager.GetString("ems_10_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurse.
        /// </summary>
        public static string ems_2_f {
            get {
                return ResourceManager.GetString("ems_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurse.
        /// </summary>
        public static string ems_2_m {
            get {
                return ResourceManager.GetString("ems_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjunct surgeon.
        /// </summary>
        public static string ems_3_f {
            get {
                return ResourceManager.GetString("ems_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjunct surgeon.
        /// </summary>
        public static string ems_3_m {
            get {
                return ResourceManager.GetString("ems_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramedic.
        /// </summary>
        public static string ems_4_f {
            get {
                return ResourceManager.GetString("ems_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramedic.
        /// </summary>
        public static string ems_4_m {
            get {
                return ResourceManager.GetString("ems_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First class surgeon.
        /// </summary>
        public static string ems_5_f {
            get {
                return ResourceManager.GetString("ems_5_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First class surgeon.
        /// </summary>
        public static string ems_5_m {
            get {
                return ResourceManager.GetString("ems_5_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medic.
        /// </summary>
        public static string ems_6_f {
            get {
                return ResourceManager.GetString("ems_6_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medic.
        /// </summary>
        public static string ems_6_m {
            get {
                return ResourceManager.GetString("ems_6_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief surgeon.
        /// </summary>
        public static string ems_7_f {
            get {
                return ResourceManager.GetString("ems_7_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief surgeon.
        /// </summary>
        public static string ems_7_m {
            get {
                return ResourceManager.GetString("ems_7_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head of emergency.
        /// </summary>
        public static string ems_8_f {
            get {
                return ResourceManager.GetString("ems_8_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head of emergency.
        /// </summary>
        public static string ems_8_m {
            get {
                return ResourceManager.GetString("ems_8_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice principal.
        /// </summary>
        public static string ems_9_f {
            get {
                return ResourceManager.GetString("ems_9_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice principal.
        /// </summary>
        public static string ems_9_m {
            get {
                return ResourceManager.GetString("ems_9_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery woman.
        /// </summary>
        public static string fastfood_f {
            get {
                return ResourceManager.GetString("fastfood_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery man.
        /// </summary>
        public static string fastfood_m {
            get {
                return ResourceManager.GetString("fastfood_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garbage woman.
        /// </summary>
        public static string gargage_f {
            get {
                return ResourceManager.GetString("gargage_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garbage man.
        /// </summary>
        public static string gargage_m {
            get {
                return ResourceManager.GetString("gargage_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prostitute.
        /// </summary>
        public static string hooker_f {
            get {
                return ResourceManager.GetString("hooker_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigolo.
        /// </summary>
        public static string hooker_m {
            get {
                return ResourceManager.GetString("hooker_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawyer.
        /// </summary>
        public static string lawer_f {
            get {
                return ResourceManager.GetString("lawer_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawyer.
        /// </summary>
        public static string lawer_m {
            get {
                return ResourceManager.GetString("lawer_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainee.
        /// </summary>
        public static string lsc_0_f {
            get {
                return ResourceManager.GetString("lsc_0_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainee.
        /// </summary>
        public static string lsc_0_m {
            get {
                return ResourceManager.GetString("lsc_0_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair woman.
        /// </summary>
        public static string lsc_1_f {
            get {
                return ResourceManager.GetString("lsc_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair man.
        /// </summary>
        public static string lsc_1_m {
            get {
                return ResourceManager.GetString("lsc_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodyworker.
        /// </summary>
        public static string lsc_2_f {
            get {
                return ResourceManager.GetString("lsc_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodyworker.
        /// </summary>
        public static string lsc_2_m {
            get {
                return ResourceManager.GetString("lsc_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanic.
        /// </summary>
        public static string lsc_3_f {
            get {
                return ResourceManager.GetString("lsc_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanic.
        /// </summary>
        public static string lsc_3_m {
            get {
                return ResourceManager.GetString("lsc_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roadside Assistance.
        /// </summary>
        public static string lsc_4_f {
            get {
                return ResourceManager.GetString("lsc_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roadside Assistance.
        /// </summary>
        public static string lsc_4_m {
            get {
                return ResourceManager.GetString("lsc_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Manager.
        /// </summary>
        public static string lsc_5_f {
            get {
                return ResourceManager.GetString("lsc_5_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Manager.
        /// </summary>
        public static string lsc_5_m {
            get {
                return ResourceManager.GetString("lsc_5_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO.
        /// </summary>
        public static string lsc_6_f {
            get {
                return ResourceManager.GetString("lsc_6_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO.
        /// </summary>
        public static string lsc_6_m {
            get {
                return ResourceManager.GetString("lsc_6_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snitch.
        /// </summary>
        public static string lspd_0_f {
            get {
                return ResourceManager.GetString("lspd_0_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snitch.
        /// </summary>
        public static string lspd_0_m {
            get {
                return ResourceManager.GetString("lspd_0_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadet.
        /// </summary>
        public static string lspd_1_f {
            get {
                return ResourceManager.GetString("lspd_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadet.
        /// </summary>
        public static string lspd_1_m {
            get {
                return ResourceManager.GetString("lspd_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer.
        /// </summary>
        public static string lspd_2_f {
            get {
                return ResourceManager.GetString("lspd_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer.
        /// </summary>
        public static string lspd_2_m {
            get {
                return ResourceManager.GetString("lspd_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sergeant.
        /// </summary>
        public static string lspd_3_f {
            get {
                return ResourceManager.GetString("lspd_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sergeant.
        /// </summary>
        public static string lspd_3_m {
            get {
                return ResourceManager.GetString("lspd_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieutenant.
        /// </summary>
        public static string lspd_4_f {
            get {
                return ResourceManager.GetString("lspd_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieutenant.
        /// </summary>
        public static string lspd_4_m {
            get {
                return ResourceManager.GetString("lspd_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        public static string lspd_5_f {
            get {
                return ResourceManager.GetString("lspd_5_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        public static string lspd_5_m {
            get {
                return ResourceManager.GetString("lspd_5_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commissar.
        /// </summary>
        public static string lspd_6_f {
            get {
                return ResourceManager.GetString("lspd_6_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commissar.
        /// </summary>
        public static string lspd_6_m {
            get {
                return ResourceManager.GetString("lspd_6_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Affairs.
        /// </summary>
        public static string lspd_7_f {
            get {
                return ResourceManager.GetString("lspd_7_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Affairs.
        /// </summary>
        public static string lspd_7_m {
            get {
                return ResourceManager.GetString("lspd_7_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayudante del Sheriff.
        /// </summary>
        public static string lssd_1_f {
            get {
                return ResourceManager.GetString("lssd_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayudante del Sheriff.
        /// </summary>
        public static string lssd_1_m {
            get {
                return ResourceManager.GetString("lssd_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayudante del Sheriff 2.
        /// </summary>
        public static string lssd_2_f {
            get {
                return ResourceManager.GetString("lssd_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayudante del Sheriff 2.
        /// </summary>
        public static string lssd_2_m {
            get {
                return ResourceManager.GetString("lssd_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detective.
        /// </summary>
        public static string lssd_3_f {
            get {
                return ResourceManager.GetString("lssd_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detective.
        /// </summary>
        public static string lssd_3_m {
            get {
                return ResourceManager.GetString("lssd_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sargento.
        /// </summary>
        public static string lssd_4_f {
            get {
                return ResourceManager.GetString("lssd_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sargento.
        /// </summary>
        public static string lssd_4_m {
            get {
                return ResourceManager.GetString("lssd_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teniente.
        /// </summary>
        public static string lssd_5_f {
            get {
                return ResourceManager.GetString("lssd_5_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teniente.
        /// </summary>
        public static string lssd_5_m {
            get {
                return ResourceManager.GetString("lssd_5_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheriff.
        /// </summary>
        public static string lssd_6_f {
            get {
                return ResourceManager.GetString("lssd_6_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheriff.
        /// </summary>
        public static string lssd_6_m {
            get {
                return ResourceManager.GetString("lssd_6_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string lstd_1_f {
            get {
                return ResourceManager.GetString("lstd_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string lstd_1_m {
            get {
                return ResourceManager.GetString("lstd_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veteran.
        /// </summary>
        public static string lstd_2_f {
            get {
                return ResourceManager.GetString("lstd_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veteran.
        /// </summary>
        public static string lstd_2_m {
            get {
                return ResourceManager.GetString("lstd_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string lstd_3_f {
            get {
                return ResourceManager.GetString("lstd_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string lstd_3_m {
            get {
                return ResourceManager.GetString("lstd_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice president.
        /// </summary>
        public static string lstd_4_f {
            get {
                return ResourceManager.GetString("lstd_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice president.
        /// </summary>
        public static string lstd_4_m {
            get {
                return ResourceManager.GetString("lstd_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President.
        /// </summary>
        public static string lstd_5_f {
            get {
                return ResourceManager.GetString("lstd_5_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President.
        /// </summary>
        public static string lstd_5_m {
            get {
                return ResourceManager.GetString("lstd_5_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanic.
        /// </summary>
        public static string mechanic_f {
            get {
                return ResourceManager.GetString("mechanic_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanic.
        /// </summary>
        public static string mechanic_m {
            get {
                return ResourceManager.GetString("mechanic_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholar.
        /// </summary>
        public static string news_1_f {
            get {
                return ResourceManager.GetString("news_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholar.
        /// </summary>
        public static string news_1_m {
            get {
                return ResourceManager.GetString("news_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journalist.
        /// </summary>
        public static string news_2_f {
            get {
                return ResourceManager.GetString("news_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journalist.
        /// </summary>
        public static string news_2_m {
            get {
                return ResourceManager.GetString("news_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcaster.
        /// </summary>
        public static string news_3_f {
            get {
                return ResourceManager.GetString("news_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcaster.
        /// </summary>
        public static string news_3_m {
            get {
                return ResourceManager.GetString("news_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice principal.
        /// </summary>
        public static string news_4_f {
            get {
                return ResourceManager.GetString("news_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice principal.
        /// </summary>
        public static string news_4_m {
            get {
                return ResourceManager.GetString("news_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string news_5_f {
            get {
                return ResourceManager.GetString("news_5_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string news_5_m {
            get {
                return ResourceManager.GetString("news_5_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilian.
        /// </summary>
        public static string none_f {
            get {
                return ResourceManager.GetString("none_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilian.
        /// </summary>
        public static string none_m {
            get {
                return ResourceManager.GetString("none_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruit.
        /// </summary>
        public static string rank1 {
            get {
                return ResourceManager.GetString("rank1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss.
        /// </summary>
        public static string rank10 {
            get {
                return ResourceManager.GetString("rank10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldier.
        /// </summary>
        public static string rank2 {
            get {
                return ResourceManager.GetString("rank2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sergant.
        /// </summary>
        public static string rank3 {
            get {
                return ResourceManager.GetString("rank3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieutenant.
        /// </summary>
        public static string rank4 {
            get {
                return ResourceManager.GetString("rank4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforcer.
        /// </summary>
        public static string rank5 {
            get {
                return ResourceManager.GetString("rank5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street boss.
        /// </summary>
        public static string rank6 {
            get {
                return ResourceManager.GetString("rank6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caporegime.
        /// </summary>
        public static string rank7 {
            get {
                return ResourceManager.GetString("rank7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consigilere.
        /// </summary>
        public static string rank8 {
            get {
                return ResourceManager.GetString("rank8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underboss.
        /// </summary>
        public static string rank9 {
            get {
                return ResourceManager.GetString("rank9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thief.
        /// </summary>
        public static string thief_f {
            get {
                return ResourceManager.GetString("thief_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thief.
        /// </summary>
        public static string thief_m {
            get {
                return ResourceManager.GetString("thief_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholar.
        /// </summary>
        public static string town_1_f {
            get {
                return ResourceManager.GetString("town_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholar.
        /// </summary>
        public static string town_1_m {
            get {
                return ResourceManager.GetString("town_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official.
        /// </summary>
        public static string town_2_f {
            get {
                return ResourceManager.GetString("town_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official.
        /// </summary>
        public static string town_2_m {
            get {
                return ResourceManager.GetString("town_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head of department.
        /// </summary>
        public static string town_3_f {
            get {
                return ResourceManager.GetString("town_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head of department.
        /// </summary>
        public static string town_3_m {
            get {
                return ResourceManager.GetString("town_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayor.
        /// </summary>
        public static string town_4_f {
            get {
                return ResourceManager.GetString("town_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayor.
        /// </summary>
        public static string town_4_m {
            get {
                return ResourceManager.GetString("town_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucker.
        /// </summary>
        public static string trucker_f {
            get {
                return ResourceManager.GetString("trucker_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucker.
        /// </summary>
        public static string trucker_m {
            get {
                return ResourceManager.GetString("trucker_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unemployed.
        /// </summary>
        public static string unemployed_f {
            get {
                return ResourceManager.GetString("unemployed_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unemployed.
        /// </summary>
        public static string unemployed_m {
            get {
                return ResourceManager.GetString("unemployed_m", resourceCulture);
            }
        }
    }
}
