//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.description {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DescRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DescRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.description.DescRes", typeof(DescRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastfood delieverer - We need fastfood deliverers. It&apos;s simple, deliver orders in time and you will get paid..
        /// </summary>
        public static string job_fastfood {
            get {
                return ResourceManager.GetString("job_fastfood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garbage man - Los Santos needs people to clean up the city. Work in pairs with a friend, one will drive and the other will collect the garbage..
        /// </summary>
        public static string job_garbage {
            get {
                return ResourceManager.GetString("job_garbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hooker - Win money selling your body, simple as that. You choose your clients and price..
        /// </summary>
        public static string job_hooker {
            get {
                return ResourceManager.GetString("job_hooker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawyer - Make money of others stupidity. .
        /// </summary>
      /*  public static string job_lawyer {
            get {
                return ResourceManager.GetString("job_lawyer", resourceCulture);
            }
        }
        */
        /// <summary>
        ///   Looks up a localized string similar to Mechanic - In Los Santos Custom we need employees that know how to treat a car..
        /// </summary>
        public static string job_mechanic {
            get {
                return ResourceManager.GetString("job_mechanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thief - If having a job is the boring way of getting money for you, maybe you prefer to get some valuable items and sell them..
        /// </summary>
        public static string job_thief {
            get {
                return ResourceManager.GetString("job_thief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucker - Trucker job text.
        /// </summary>
        public static string job_trucker {
            get {
                return ResourceManager.GetString("job_trucker", resourceCulture);
            }
        }

        public static string job_oceancleaner
        {
            get
            {
                return ResourceManager.GetString("oceancleaner_job", resourceCulture);
            }
        }

        public static string job_deliveryman
        {
            get
            {
                return ResourceManager.GetString("deliveryman_job", resourceCulture);
            }
        }
    }
}
