//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.help {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.help.HelpRes", typeof(HelpRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /do [Message].
        /// </summary>
        public static string _do {
            get {
                return ResourceManager.GetString("do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /a [Message].
        /// </summary>
        public static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /aticket [Ticket id.] [Help answer message].
        /// </summary>
        public static string a_ticket {
            get {
                return ResourceManager.GetString("a_ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /accept [Order|Service|Interview|Money|Repaint].
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access ATM.
        /// </summary>
        public static string access_atm {
            get {
                return ResourceManager.GetString("access_atm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string action_business {
            get {
                return ResourceManager.GetString("action_business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut plant.
        /// </summary>
        public static string action_plant {
            get {
                return ResourceManager.GetString("action_plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tramitate.
        /// </summary>
        public static string action_tramitate {
            get {
                return ResourceManager.GetString("action_tramitate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /admin [Message].
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /ame [Message].
        /// </summary>
        public static string ame {
            get {
                return ResourceManager.GetString("ame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /announce [Announcement message].
        /// </summary>
        public static string announce {
            get {
                return ResourceManager.GetString("announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /attend [Report id.].
        /// </summary>
        public static string attend {
            get {
                return ResourceManager.GetString("attend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /ban [Player id./Player name] [Reason].
        /// </summary>
        public static string ban {
            get {
                return ResourceManager.GetString("ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /breathalyzer [Player id./Player name].
        /// </summary>
        public static string breathalyzer {
            get {
                return ResourceManager.GetString("breathalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /bring [Player id./Player name].
        /// </summary>
        public static string bring {
            get {
                return ResourceManager.GetString("bring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /business [Info|Create|Modify|Remove].
        /// </summary>
        public static string business {
            get {
                return ResourceManager.GetString("business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /business create [Business type] [Inner/Outer].
        /// </summary>
        public static string business_create {
            get {
                return ResourceManager.GetString("business_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /business modify [Name|Type].
        /// </summary>
        public static string business_modify {
            get {
                return ResourceManager.GetString("business_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /business modify name [Text].
        /// </summary>
        public static string business_modify_name {
            get {
                return ResourceManager.GetString("business_modify_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /business modify type [Value].
        /// </summary>
        public static string business_modify_type {
            get {
                return ResourceManager.GetString("business_modify_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /cancel [Order|Service|Interview|Money|Repaint].
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /character [Bank|Money|Faction|Rank|Job|Dimension] [Player id./Player name] [Value].
        /// </summary>
        public static string character {
            get {
                return ResourceManager.GetString("character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /clearreport [Report id.].
        /// </summary>
        public static string clear_report {
            get {
                return ResourceManager.GetString("clear_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /complement [Mask|Bag|Accessory|Hat|Glasses|Earrings] [Wear|Remove].
        /// </summary>
        public static string complement {
            get {
                return ResourceManager.GetString("complement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /computer [Player id./Player name].
        /// </summary>
        public static string computer {
            get {
                return ResourceManager.GetString("computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /contacts [Number|View|Add|Modify|Remove|SMS].
        /// </summary>
        public static string contacts {
            get {
                return ResourceManager.GetString("contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /control [Load|Save|Rename|Delete|Clear].
        /// </summary>
        public static string control {
            get {
                return ResourceManager.GetString("control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /coord [Pos. X] [Pos. Y] [Pos. Z].
        /// </summary>
        public static string coord {
            get {
                return ResourceManager.GetString("coord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /cutinterview [Player id./Player name].
        /// </summary>
        public static string cut_interview {
            get {
                return ResourceManager.GetString("cut_interview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /dismiss [Player id./Player name].
        /// </summary>
        public static string dismiss {
            get {
                return ResourceManager.GetString("dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /drivingschool [Car|Motorcycle].
        /// </summary>
        public static string driving_school {
            get {
                return ResourceManager.GetString("driving_school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /ed [Message].
        /// </summary>
        public static string ed {
            get {
                return ResourceManager.GetString("ed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter building.
        /// </summary>
        public static string enter_building {
            get {
                return ResourceManager.GetString("enter_building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter business.
        /// </summary>
        public static string enter_business {
            get {
                return ResourceManager.GetString("enter_business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter house.
        /// </summary>
        public static string enter_house {
            get {
                return ResourceManager.GetString("enter_house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /equipment [Basic|Ammunition|Weapon] [Pistol|Assault|Machinegun|Sniper|Shotgun].
        /// </summary>
        public static string equipment {
            get {
                return ResourceManager.GetString("equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /equipment weapon [Pistol|Revolver|Asault|Machinegun|Sniper|Shotgun].
        /// </summary>
        public static string equipment_weapon {
            get {
                return ResourceManager.GetString("equipment_weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit business.
        /// </summary>
        public static string exit_business {
            get {
                return ResourceManager.GetString("exit_business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit house.
        /// </summary>
        public static string exit_house {
            get {
                return ResourceManager.GetString("exit_house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit interior.
        /// </summary>
        public static string exit_interior {
            get {
                return ResourceManager.GetString("exit_interior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit lobby.
        /// </summary>
        public static string exit_lobby {
            get {
                return ResourceManager.GetString("exit_lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /extract [Player id./Player name].
        /// </summary>
        public static string extract {
            get {
                return ResourceManager.GetString("extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /f [Message].
        /// </summary>
        public static string f {
            get {
                return ResourceManager.GetString("f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /fine [Name] [Surname] [Price] [Reason].
        /// </summary>
        public static string fine {
            get {
                return ResourceManager.GetString("fine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /fr [Message].
        /// </summary>
        public static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /frequency [Create|Modify|Remove|Connect|Disconnect].
        /// </summary>
        public static string frequency {
            get {
                return ResourceManager.GetString("frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /frequency connect [Frequency id.] [Password].
        /// </summary>
        public static string frequency_connect {
            get {
                return ResourceManager.GetString("frequency_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /frequency create [Password].
        /// </summary>
        public static string frequency_create {
            get {
                return ResourceManager.GetString("frequency_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /frequency modify [Password].
        /// </summary>
        public static string frequency_modify {
            get {
                return ResourceManager.GetString("frequency_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /frisk [Player id./Player name].
        /// </summary>
        public static string frisk {
            get {
                return ResourceManager.GetString("frisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /furniture [Place|Move|Remove].
        /// </summary>
        public static string furniture {
            get {
                return ResourceManager.GetString("furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /garbage [Route|Pickup|Cancel].
        /// </summary>
        public static string garbage {
            get {
                return ResourceManager.GetString("garbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /give [Player id./Player name].
        /// </summary>
        public static string give {
            get {
                return ResourceManager.GetString("give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /go [Workshop | Electronics | Police | Townhall | License | Hospital | Mechanic | News | Bahama | Garbage].
        /// </summary>
        public static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /gun [Player id./Player name] [Weapon] [Bullets].
        /// </summary>
        public static string gun {
            get {
                return ResourceManager.GetString("gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /handcuff [Player id./Player name].
        /// </summary>
        public static string handcuff {
            get {
                return ResourceManager.GetString("handcuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /heal [Player id./Player name].
        /// </summary>
        public static string heal {
            get {
                return ResourceManager.GetString("heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /health [Player id./Player name] [Amount].
        /// </summary>
        public static string health {
            get {
                return ResourceManager.GetString("health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /house [Info|Create|Modify|Remove|Tp].
        /// </summary>
        public static string house {
            get {
                return ResourceManager.GetString("house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /house [Type].
        /// </summary>
        public static string house_create {
            get {
                return ResourceManager.GetString("house_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /house tp [House id.].
        /// </summary>
        public static string house_goto {
            get {
                return ResourceManager.GetString("house_goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /house info [(Opt.) House id.].
        /// </summary>
        public static string house_info {
            get {
                return ResourceManager.GetString("house_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /house modify [Interior|Price|State|Rent|Owner|Name].
        /// </summary>
        public static string house_modify {
            get {
                return ResourceManager.GetString("house_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /house modify [Interior|Price|State|Rent] [Value].
        /// </summary>
        public static string house_modify_int {
            get {
                return ResourceManager.GetString("house_modify_int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /house modify [Owner|Name] [Text].
        /// </summary>
        public static string house_modify_string {
            get {
                return ResourceManager.GetString("house_modify_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /incriminate [Player id./Player name].
        /// </summary>
        public static string incriminate {
            get {
                return ResourceManager.GetString("incriminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /info [Player id./Player name].
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /interior [Create|Modify|Remove|Tp].
        /// </summary>
        public static string interior {
            get {
                return ResourceManager.GetString("interior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /interior create [Type].
        /// </summary>
        public static string interior_create {
            get {
                return ResourceManager.GetString("interior_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /interior tp [Interior id.].
        /// </summary>
        public static string interior_goto {
            get {
                return ResourceManager.GetString("interior_goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /interior modify [Type|Mark|Name] [Value].
        /// </summary>
        public static string interior_modify {
            get {
                return ResourceManager.GetString("interior_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /interview [Player id./Player name].
        /// </summary>
        public static string interview {
            get {
                return ResourceManager.GetString("interview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /jail [Player id./Player name] [Minutes] [Reason].
        /// </summary>
        public static string jail {
            get {
                return ResourceManager.GetString("jail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /job [Info|Accept|Leave].
        /// </summary>
        public static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /keys [Lend|Drop] [Vehicle id.] [Player id./Player name].
        /// </summary>
        public static string keys {
            get {
                return ResourceManager.GetString("keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /kick [Player id./Player name] [Reason].
        /// </summary>
        public static string kick {
            get {
                return ResourceManager.GetString("kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /license [Give|Remove] [Weapon|Car|Motorcycle] [Player id./Player name].
        /// </summary>
        public static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /locate [Vehicle id.].
        /// </summary>
        public static string locate {
            get {
                return ResourceManager.GetString("locate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage characters.
        /// </summary>
        public static string manage_characters {
            get {
                return ResourceManager.GetString("manage_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /me [Message].
        /// </summary>
        public static string me {
            get {
                return ResourceManager.GetString("me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /megaphone [Message].
        /// </summary>
        public static string megaphone {
            get {
                return ResourceManager.GetString("megaphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /n [News message].
        /// </summary>
        public static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /ooc [Message].
        /// </summary>
        public static string ooc {
            get {
                return ResourceManager.GetString("ooc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /parking [Info|Create|Modify|Remove].
        /// </summary>
        public static string parking {
            get {
                return ResourceManager.GetString("parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /parking create [0 Public parking | 1 Garage | 2 Scrapyard | 3 Police deposit].
        /// </summary>
        public static string parking_create {
            get {
                return ResourceManager.GetString("parking_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /parking modify [House|Places|Type] [Value].
        /// </summary>
        public static string parking_modify {
            get {
                return ResourceManager.GetString("parking_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /pay [Player id./Player name] [Amount].
        /// </summary>
        public static string pay {
            get {
                return ResourceManager.GetString("pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /pd [Message].
        /// </summary>
        public static string pd {
            get {
                return ResourceManager.GetString("pd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /pm [Player id./Player name] [Message].
        /// </summary>
        public static string pm {
            get {
                return ResourceManager.GetString("pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /points [Give|Remove|Set] [Player id./Player name] [Amount].
        /// </summary>
        public static string points {
            get {
                return ResourceManager.GetString("points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /prize [Player id./Player name] [Amount] [Reason].
        /// </summary>
        public static string prize {
            get {
                return ResourceManager.GetString("prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /purchase [Amount].
        /// </summary>
        public static string purchase {
            get {
                return ResourceManager.GetString("purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /put [Cone|Beacon|Barrier|Spikes].
        /// </summary>
        public static string put {
            get {
                return ResourceManager.GetString("put", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /r [Message].
        /// </summary>
        public static string r {
            get {
                return ResourceManager.GetString("r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /rank [Player id./Player name] [Value].
        /// </summary>
        public static string rank {
            get {
                return ResourceManager.GetString("rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /reanimate [Player id./Player name].
        /// </summary>
        public static string reanimate {
            get {
                return ResourceManager.GetString("reanimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /recon [Player id./Player name].
        /// </summary>
        public static string recon {
            get {
                return ResourceManager.GetString("recon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /recruit [Player id./Player name].
        /// </summary>
        public static string recruit {
            get {
                return ResourceManager.GetString("recruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /refuel [Price (0 for full tank)].
        /// </summary>
        public static string refuel {
            get {
                return ResourceManager.GetString("refuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /remove [Cone|Beacon|Barrier|Spikes].
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /rentable [Amount].
        /// </summary>
        public static string rentable {
            get {
                return ResourceManager.GetString("rentable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /repaint [Vehicle id.].
        /// </summary>
        public static string repaint {
            get {
                return ResourceManager.GetString("repaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /repair [Vehicle id.] [Chassis|Doors|Tyres|Windows|Engine] [Price].
        /// </summary>
        public static string repair {
            get {
                return ResourceManager.GetString("repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /revive [Player id./Player name].
        /// </summary>
        public static string revive {
            get {
                return ResourceManager.GetString("revive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /say [Message].
        /// </summary>
        public static string say {
            get {
                return ResourceManager.GetString("say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /sell [Vehicle|House|Fish] [Vehicle id./House id.] [Player id./Player name] [Price].
        /// </summary>
        public static string sell {
            get {
                return ResourceManager.GetString("sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /sell house [House id.] [Player id./Player name] [Price] (70% of its value when not filling player neither price).
        /// </summary>
        public static string sell_house {
            get {
                return ResourceManager.GetString("sell_house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /sell vehicle [Vehicle id.] [Player id./Player name] [Price].
        /// </summary>
        public static string sell_vehicle {
            get {
                return ResourceManager.GetString("sell_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /service [Sex|Oral] [Player id./Player name] [Price].
        /// </summary>
        public static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /show [Player id./Player name] [Licenses|Identification|Insurance].
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show catalog.
        /// </summary>
        public static string show_catalog {
            get {
                return ResourceManager.GetString("show_catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /skin [Ped model name].
        /// </summary>
        public static string skin {
            get {
                return ResourceManager.GetString("skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /sms [Number] [Message].
        /// </summary>
        public static string sms {
            get {
                return ResourceManager.GetString("sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /ticket [Help message].
        /// </summary>
        public static string ticket {
            get {
                return ResourceManager.GetString("ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /tp [Player id./Player name].
        /// </summary>
        public static string tp {
            get {
                return ResourceManager.GetString("tp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /trunk [Open|Close|Store|Withdraw].
        /// </summary>
        public static string trunk {
            get {
                return ResourceManager.GetString("trunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /unpark [Vehicle id.].
        /// </summary>
        public static string unpark {
            get {
                return ResourceManager.GetString("unpark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /vehicle [Info|Create|Modify|Remove|Repair|Lock|Start|Bring|Tp].
        /// </summary>
        public static string vehicle {
            get {
                return ResourceManager.GetString("vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /vehicle bring [Vehicle id.].
        /// </summary>
        public static string vehicle_bring {
            get {
                return ResourceManager.GetString("vehicle_bring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /vehicle modify color [Primary color (R,G,B)] [Secondary color (R,G,B)].
        /// </summary>
        public static string vehicle_color {
            get {
                return ResourceManager.GetString("vehicle_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /vehicle create [Model] [Primary color (R,G,B)] [Secondary color (R,G,B)].
        /// </summary>
        public static string vehicle_create {
            get {
                return ResourceManager.GetString("vehicle_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /vehicle remove [Vehicle id.].
        /// </summary>
        public static string vehicle_delete {
            get {
                return ResourceManager.GetString("vehicle_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /vehicle modify dimension [Vehicle id.] [Value].
        /// </summary>
        public static string vehicle_dimension {
            get {
                return ResourceManager.GetString("vehicle_dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /vehicle modify faction [Value].
        /// </summary>
        public static string vehicle_faction {
            get {
                return ResourceManager.GetString("vehicle_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /vehicle modify gas [Vehicle id.] [Value].
        /// </summary>
        public static string vehicle_gas {
            get {
                return ResourceManager.GetString("vehicle_gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /vehicle tp [Vehicle id.].
        /// </summary>
        public static string vehicle_goto {
            get {
                return ResourceManager.GetString("vehicle_goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /vehicle modify [Color|Dimension|Owner|Faction|Position|Gas].
        /// </summary>
        public static string vehicle_modify {
            get {
                return ResourceManager.GetString("vehicle_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /vehicle modify owner [Name] [Surname].
        /// </summary>
        public static string vehicle_owner {
            get {
                return ResourceManager.GetString("vehicle_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /weather [0-12].
        /// </summary>
        public static string weather {
            get {
                return ResourceManager.GetString("weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /whisper [Message].
        /// </summary>
        public static string whisper {
            get {
                return ResourceManager.GetString("whisper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: /yell [Message].
        /// </summary>
        public static string yell {
            get {
                return ResourceManager.GetString("yell", resourceCulture);
            }
        }
    }
}
