//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.general {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GenRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.general.GenRes", typeof(GenRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~r~[ADMIN] .
        /// </summary>
        public static string admin_notice {
            get {
                return ResourceManager.GetString("admin_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age: .
        /// </summary>
        public static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ANNOUNCEMENT] .
        /// </summary>
        public static string announcement {
            get {
                return ResourceManager.GetString("announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status: attended by .
        /// </summary>
        public static string attended_by {
            get {
                return ResourceManager.GetString("attended_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank: .
        /// </summary>
        public static string bank {
            get {
                return ResourceManager.GetString("bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank interest: .
        /// </summary>
        public static string bank_interest {
            get {
                return ResourceManager.GetString("bank_interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string bank_op_deposit {
            get {
                return ResourceManager.GetString("bank_op_deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string bank_op_transfer {
            get {
                return ResourceManager.GetString("bank_op_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string bank_op_withdraw {
            get {
                return ResourceManager.GetString("bank_op_withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat dealer.
        /// </summary>
        public static string boat_dealer {
            get {
                return ResourceManager.GetString("boat_dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string business {
            get {
                return ResourceManager.GetString("business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car dealer.
        /// </summary>
        public static string car_dealer {
            get {
                return ResourceManager.GetString("car_dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casino.
        /// </summary>
        public static string casino {
            get {
                return ResourceManager.GetString("casino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the command above to see the vehicle list.
        /// </summary>
        public static string catalog_help {
            get {
                return ResourceManager.GetString("catalog_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press F to change your character.
        /// </summary>
        public static string character_help {
            get {
                return ResourceManager.GetString("character_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  at phone: .
        /// </summary>
        public static string chat_phone {
            get {
                return ResourceManager.GetString("chat_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  at radio: .
        /// </summary>
        public static string chat_radio {
            get {
                return ResourceManager.GetString("chat_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  says: .
        /// </summary>
        public static string chat_say {
            get {
                return ResourceManager.GetString("chat_say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  whispers: .
        /// </summary>
        public static string chat_whisper {
            get {
                return ResourceManager.GetString("chat_whisper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shouts:.
        /// </summary>
        public static string chat_yell {
            get {
                return ResourceManager.GetString("chat_yell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1} used {2}.
        /// </summary>
        public static string command_used {
            get {
                return ResourceManager.GetString("command_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dev.
        /// </summary>
        public static string deliveryman_job {
            get {
                return ResourceManager.GetString("deliveryman_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving school.
        /// </summary>
        public static string driving_school {
            get {
                return ResourceManager.GetString("driving_school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency medical services.
        /// </summary>
        public static string emergency_faction {
            get {
                return ResourceManager.GetString("emergency_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the command above to get the police equipment.
        /// </summary>
        public static string equipment_help {
            get {
                return ResourceManager.GetString("equipment_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date: .
        /// </summary>
        public static string expiry {
            get {
                return ResourceManager.GetString("expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra income: .
        /// </summary>
        public static string extra_income {
            get {
                return ResourceManager.GetString("extra_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faction: .
        /// </summary>
        public static string faction {
            get {
                return ResourceManager.GetString("faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMS.
        /// </summary>
        public static string faction_ems {
            get {
                return ResourceManager.GetString("faction_ems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal Faction.
        /// </summary>
        public static string faction_i1 {
            get {
                return ResourceManager.GetString("faction_i1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSPD.
        /// </summary>
        public static string faction_lspd {
            get {
                return ResourceManager.GetString("faction_lspd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weazel News.
        /// </summary>
        public static string faction_news {
            get {
                return ResourceManager.GetString("faction_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town hall.
        /// </summary>
        public static string faction_townhall {
            get {
                return ResourceManager.GetString("faction_townhall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport service.
        /// </summary>
        public static string faction_transport {
            get {
                return ResourceManager.GetString("faction_transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastfood deliverer job.
        /// </summary>
        public static string fastfood_job {
            get {
                return ResourceManager.GetString("fastfood_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment of fines.
        /// </summary>
        public static string fines_payment {
            get {
                return ResourceManager.GetString("fines_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage.
        /// </summary>
        public static string garage {
            get {
                return ResourceManager.GetString("garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garbage man job.
        /// </summary>
        public static string garbage_job {
            get {
                return ResourceManager.GetString("garbage_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest .
        /// </summary>
        public static string guest {
            get {
                return ResourceManager.GetString("guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ~b~/help ~w~command whenever you want to get general information..
        /// </summary>
        public static string help_hint {
            get {
                return ResourceManager.GetString("help_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hooker service.
        /// </summary>
        public static string hooker {
            get {
                return ResourceManager.GetString("hooker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital.
        /// </summary>
        public static string hospital {
            get {
                return ResourceManager.GetString("hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string house {
            get {
                return ResourceManager.GetString("house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __________Your House(ID: {0})__________.
        /// </summary>
        public static string house_check_title {
            get {
                return ResourceManager.GetString("house_check_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House sale.
        /// </summary>
        public static string house_sale {
            get {
                return ResourceManager.GetString("house_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House taxes from .
        /// </summary>
        public static string house_taxes_from {
            get {
                return ResourceManager.GetString("house_taxes_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houses: .
        /// </summary>
        public static string houses {
            get {
                return ResourceManager.GetString("houses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification card.
        /// </summary>
        public static string identification {
            get {
                return ResourceManager.GetString("identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interviewer .
        /// </summary>
        public static string interviewer {
            get {
                return ResourceManager.GetString("interviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPL: .
        /// </summary>
        public static string ipl {
            get {
                return ResourceManager.GetString("ipl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job: .
        /// </summary>
        public static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the command above to get more information about the job.
        /// </summary>
        public static string job_help {
            get {
                return ResourceManager.GetString("job_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law Services.
        /// </summary>
        public static string lawyer {
            get {
                return ResourceManager.GetString("lawyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lent vehicles: .
        /// </summary>
        public static string lent_vehicles {
            get {
                return ResourceManager.GetString("lent_vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanic job.
        /// </summary>
        public static string mechanic_job {
            get {
                return ResourceManager.GetString("mechanic_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical insurance.
        /// </summary>
        public static string medical_insurance {
            get {
                return ResourceManager.GetString("medical_insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online members:.
        /// </summary>
        public static string members_online {
            get {
                return ResourceManager.GetString("members_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money: .
        /// </summary>
        public static string money {
            get {
                return ResourceManager.GetString("money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcycle dealer.
        /// </summary>
        public static string motorcycle_dealer {
            get {
                return ResourceManager.GetString("motorcycle_dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weazel News announcement.
        /// </summary>
        public static string news_announce {
            get {
                return ResourceManager.GetString("news_announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weazel News.
        /// </summary>
        public static string news_faction {
            get {
                return ResourceManager.GetString("news_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weazel News prize.
        /// </summary>
        public static string news_prize {
            get {
                return ResourceManager.GetString("news_prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No faction.
        /// </summary>
        public static string no_faction {
            get {
                return ResourceManager.GetString("no_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rank.
        /// </summary>
        public static string no_rank {
            get {
                return ResourceManager.GetString("no_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no pending report to attend..
        /// </summary>
        public static string not_faction_warning {
            get {
                return ResourceManager.GetString("not_faction_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocean Cleaner.
        /// </summary>
        public static string oceancleaner_job {
            get {
                return ResourceManager.GetString("oceancleaner_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned vehicles: .
        /// </summary>
        public static string owned_vehicles {
            get {
                return ResourceManager.GetString("owned_vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner: .
        /// </summary>
        public static string owner {
            get {
                return ResourceManager.GetString("owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pawn shop.
        /// </summary>
        public static string pawn_shop {
            get {
                return ResourceManager.GetString("pawn_shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment between players.
        /// </summary>
        public static string payment_players {
            get {
                return ResourceManager.GetString("payment_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Phone] .
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place: .
        /// </summary>
        public static string place {
            get {
                return ResourceManager.GetString("place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played: .
        /// </summary>
        public static string played_time {
            get {
                return ResourceManager.GetString("played_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private message from .
        /// </summary>
        public static string pm_from {
            get {
                return ResourceManager.GetString("pm_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private message to .
        /// </summary>
        public static string pm_to {
            get {
                return ResourceManager.GetString("pm_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police depot.
        /// </summary>
        public static string police_depot {
            get {
                return ResourceManager.GetString("police_depot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police department.
        /// </summary>
        public static string police_faction {
            get {
                return ResourceManager.GetString("police_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police station.
        /// </summary>
        public static string police_station {
            get {
                return ResourceManager.GetString("police_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: .
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public parking.
        /// </summary>
        public static string public_parking {
            get {
                return ResourceManager.GetString("public_parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Radio] .
        /// </summary>
        public static string radio {
            get {
                return ResourceManager.GetString("radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank: .
        /// </summary>
        public static string rank {
            get {
                return ResourceManager.GetString("rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency reports:.
        /// </summary>
        public static string reports_header {
            get {
                return ResourceManager.GetString("reports_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role points: .
        /// </summary>
        public static string role_points {
            get {
                return ResourceManager.GetString("role_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been assigned east route..
        /// </summary>
        public static string route_east {
            get {
                return ResourceManager.GetString("route_east", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been assigned north route..
        /// </summary>
        public static string route_north {
            get {
                return ResourceManager.GetString("route_north", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been assigned south route..
        /// </summary>
        public static string route_south {
            get {
                return ResourceManager.GetString("route_south", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been assigned west route..
        /// </summary>
        public static string route_west {
            get {
                return ResourceManager.GetString("route_west", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary: .
        /// </summary>
        public static string salary {
            get {
                return ResourceManager.GetString("salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrapyard.
        /// </summary>
        public static string scrapyard {
            get {
                return ResourceManager.GetString("scrapyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex: .
        /// </summary>
        public static string sex {
            get {
                return ResourceManager.GetString("sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string sex_female {
            get {
                return ResourceManager.GetString("sex_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string sex_male {
            get {
                return ResourceManager.GetString("sex_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SASD.
        /// </summary>
        public static string sheriff_faction {
            get {
                return ResourceManager.GetString("sheriff_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS from .
        /// </summary>
        public static string sms_from {
            get {
                return ResourceManager.GetString("sms_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House state: Occupied.
        /// </summary>
        public static string state_occupied {
            get {
                return ResourceManager.GetString("state_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House state: For rent.
        /// </summary>
        public static string state_rent {
            get {
                return ResourceManager.GetString("state_rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House state: For sale.
        /// </summary>
        public static string state_sale {
            get {
                return ResourceManager.GetString("state_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi license.
        /// </summary>
        public static string taxi_license {
            get {
                return ResourceManager.GetString("taxi_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thief.
        /// </summary>
        public static string thief_job {
            get {
                return ResourceManager.GetString("thief_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ~b~/ticket ~w~command to ask for help from the staff..
        /// </summary>
        public static string ticket_hint {
            get {
                return ResourceManager.GetString("ticket_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: .
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: .
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town hall.
        /// </summary>
        public static string townhall {
            get {
                return ResourceManager.GetString("townhall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town hall.
        /// </summary>
        public static string townhall_faction {
            get {
                return ResourceManager.GetString("townhall_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the command above to get the available formalities.
        /// </summary>
        public static string townhall_help {
            get {
                return ResourceManager.GetString("townhall_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport services.
        /// </summary>
        public static string transport_faction {
            get {
                return ResourceManager.GetString("transport_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucker.
        /// </summary>
        public static string trucker_job {
            get {
                return ResourceManager.GetString("trucker_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status: unattended.
        /// </summary>
        public static string unattended {
            get {
                return ResourceManager.GetString("unattended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unemployed.
        /// </summary>
        public static string unemployed {
            get {
                return ResourceManager.GetString("unemployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _________Information about vehicle with ID {0}_________.
        /// </summary>
        public static string vehicle_check_title {
            get {
                return ResourceManager.GetString("vehicle_check_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model: .
        /// </summary>
        public static string vehicle_model {
            get {
                return ResourceManager.GetString("vehicle_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate: .
        /// </summary>
        public static string vehicle_plate {
            get {
                return ResourceManager.GetString("vehicle_plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle sale.
        /// </summary>
        public static string vehicle_sale {
            get {
                return ResourceManager.GetString("vehicle_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes from .
        /// </summary>
        public static string vehicle_taxes_from {
            get {
                return ResourceManager.GetString("vehicle_taxes_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weapon crate.
        /// </summary>
        public static string weapon_crate {
            get {
                return ResourceManager.GetString("weapon_crate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weazel News.
        /// </summary>
        public static string weazel_news {
            get {
                return ResourceManager.GetString("weazel_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the ~y~/welcome ~w~ to find out more about the server..
        /// </summary>
        public static string welcome_hint {
            get {
                return ResourceManager.GetString("welcome_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ~b~Oceanic~w~ Roleplay. We hope you enjoy your time in the city!.
        /// </summary>
        public static string welcome_message {
            get {
                return ResourceManager.GetString("welcome_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  years.
        /// </summary>
        public static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
    }
}
