//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.items {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.items.ItemRes", typeof(ItemRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advanced rifle.
        /// </summary>
        public static string advanced_rifle {
            get {
                return ResourceManager.GetString("advanced_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AP Pistol.
        /// </summary>
        public static string ap_pistol {
            get {
                return ResourceManager.GetString("ap_pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assault rifle.
        /// </summary>
        public static string assault_rifle {
            get {
                return ResourceManager.GetString("assault_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assault shotgun.
        /// </summary>
        public static string assault_shotgun {
            get {
                return ResourceManager.GetString("assault_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assault SMG.
        /// </summary>
        public static string assault_smg {
            get {
                return ResourceManager.GetString("assault_smg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bait.
        /// </summary>
        public static string bait {
            get {
                return ResourceManager.GetString("bait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bat.
        /// </summary>
        public static string bat {
            get {
                return ResourceManager.GetString("bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Beer bottle.
        /// </summary>
        public static string beer_bottle {
            get {
                return ResourceManager.GetString("beer_bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Beer pack.
        /// </summary>
        public static string beer_pack {
            get {
                return ResourceManager.GetString("beer_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bullpup rifle.
        /// </summary>
        public static string bullpup_rifle {
            get {
                return ResourceManager.GetString("bullpup_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bullpup shotgun.
        /// </summary>
        public static string bullpup_shotgun {
            get {
                return ResourceManager.GetString("bullpup_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Burger.
        /// </summary>
        public static string burger {
            get {
                return ResourceManager.GetString("burger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camera.
        /// </summary>
        public static string camera {
            get {
                return ResourceManager.GetString("camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Candies.
        /// </summary>
        public static string candy {
            get {
                return ResourceManager.GetString("candy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carbine.
        /// </summary>
        public static string carbine_rifle {
            get {
                return ResourceManager.GetString("carbine_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cava bottle.
        /// </summary>
        public static string cava_bottle {
            get {
                return ResourceManager.GetString("cava_bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RedWood cigarettes.
        /// </summary>
        public static string cigarettes {
            get {
                return ResourceManager.GetString("cigarettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coffee.
        /// </summary>
        public static string coffee {
            get {
                return ResourceManager.GetString("coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FunCola.
        /// </summary>
        public static string cola {
            get {
                return ResourceManager.GetString("cola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combat PDW.
        /// </summary>
        public static string combat_pdw {
            get {
                return ResourceManager.GetString("combat_pdw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compact rifle.
        /// </summary>
        public static string compact_rifle {
            get {
                return ResourceManager.GetString("compact_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crowbar.
        /// </summary>
        public static string crowbar {
            get {
                return ResourceManager.GetString("crowbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Double barrel shotgun.
        /// </summary>
        public static string double_barrel_shotgun {
            get {
                return ResourceManager.GetString("double_barrel_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Energy drink.
        /// </summary>
        public static string energy_drink {
            get {
                return ResourceManager.GetString("energy_drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fish.
        /// </summary>
        public static string fish {
            get {
                return ResourceManager.GetString("fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fishing rod.
        /// </summary>
        public static string fishing_rod {
            get {
                return ResourceManager.GetString("fishing_rod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flashlight.
        /// </summary>
        public static string flashlight {
            get {
                return ResourceManager.GetString("flashlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Golf club.
        /// </summary>
        public static string golf_club {
            get {
                return ResourceManager.GetString("golf_club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hammer.
        /// </summary>
        public static string hammer {
            get {
                return ResourceManager.GetString("hammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hatchet.
        /// </summary>
        public static string hatchet {
            get {
                return ResourceManager.GetString("hatchet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Heavy pistol.
        /// </summary>
        public static string heavy_pistol {
            get {
                return ResourceManager.GetString("heavy_pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Heavy shotgun.
        /// </summary>
        public static string heavy_shotgun {
            get {
                return ResourceManager.GetString("heavy_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Heavy sniper rifle.
        /// </summary>
        public static string heavy_sniper {
            get {
                return ResourceManager.GetString("heavy_sniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hot dog.
        /// </summary>
        public static string hotdog {
            get {
                return ResourceManager.GetString("hotdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jerrycan.
        /// </summary>
        public static string jerrycan {
            get {
                return ResourceManager.GetString("jerrycan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juice.
        /// </summary>
        public static string juice {
            get {
                return ResourceManager.GetString("juice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Knife.
        /// </summary>
        public static string knife {
            get {
                return ResourceManager.GetString("knife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Knuckle duster.
        /// </summary>
        public static string knucle_duster {
            get {
                return ResourceManager.GetString("knucle_duster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Machine pistol.
        /// </summary>
        public static string machine_pistol {
            get {
                return ResourceManager.GetString("machine_pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marksman rifle.
        /// </summary>
        public static string marksman_rifle {
            get {
                return ResourceManager.GetString("marksman_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Micro SMG.
        /// </summary>
        public static string micro_smg {
            get {
                return ResourceManager.GetString("micro_smg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pistol.
        /// </summary>
        public static string pistol {
            get {
                return ResourceManager.GetString("pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pistol 50.
        /// </summary>
        public static string pistol_50 {
            get {
                return ResourceManager.GetString("pistol_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pistol ammunition.
        /// </summary>
        public static string pistol_ammo {
            get {
                return ResourceManager.GetString("pistol_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        public static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pump shotgun.
        /// </summary>
        public static string pump_shotgun {
            get {
                return ResourceManager.GetString("pump_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revolver.
        /// </summary>
        public static string revolver {
            get {
                return ResourceManager.GetString("revolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assault rifle ammunition.
        /// </summary>
        public static string rifle_ammo {
            get {
                return ResourceManager.GetString("rifle_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sandwich.
        /// </summary>
        public static string sandwich {
            get {
                return ResourceManager.GetString("sandwich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sawn-off shotgun.
        /// </summary>
        public static string sawn_off_shotgun {
            get {
                return ResourceManager.GetString("sawn_off_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shotgun ammunition.
        /// </summary>
        public static string shotgun_ammo {
            get {
                return ResourceManager.GetString("shotgun_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Smartphone.
        /// </summary>
        public static string smartphone {
            get {
                return ResourceManager.GetString("smartphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMG.
        /// </summary>
        public static string smg {
            get {
                return ResourceManager.GetString("smg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Machine gun ammunition.
        /// </summary>
        public static string smg_ammo {
            get {
                return ResourceManager.GetString("smg_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sniper rifle ammunition.
        /// </summary>
        public static string sniper_ammo {
            get {
                return ResourceManager.GetString("sniper_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sniper rifle.
        /// </summary>
        public static string sniper_rifle {
            get {
                return ResourceManager.GetString("sniper_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Special carbine.
        /// </summary>
        public static string special_carbine {
            get {
                return ResourceManager.GetString("special_carbine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stolen items.
        /// </summary>
        public static string stolen_items {
            get {
                return ResourceManager.GetString("stolen_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Switchblade.
        /// </summary>
        public static string switchblade {
            get {
                return ResourceManager.GetString("switchblade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Walkie-Talkie.
        /// </summary>
        public static string walkie {
            get {
                return ResourceManager.GetString("walkie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrench.
        /// </summary>
        public static string wrench {
            get {
                return ResourceManager.GetString("wrench", resourceCulture);
            }
        }
    }
}
