//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.items {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.items.ItemRes", typeof(ItemRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetone.
        /// </summary>
        public static string acetone {
            get {
                return ResourceManager.GetString("acetone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced rifle.
        /// </summary>
        public static string advanced_rifle {
            get {
                return ResourceManager.GetString("advanced_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP Pistol.
        /// </summary>
        public static string ap_pistol {
            get {
                return ResourceManager.GetString("ap_pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assault rifle.
        /// </summary>
        public static string assault_rifle {
            get {
                return ResourceManager.GetString("assault_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assault shotgun.
        /// </summary>
        public static string assault_shotgun {
            get {
                return ResourceManager.GetString("assault_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assault SMG.
        /// </summary>
        public static string assault_smg {
            get {
                return ResourceManager.GetString("assault_smg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bait.
        /// </summary>
        public static string bait {
            get {
                return ResourceManager.GetString("bait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandage.
        /// </summary>
        public static string bandage {
            get {
                return ResourceManager.GetString("bandage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bat.
        /// </summary>
        public static string bat {
            get {
                return ResourceManager.GetString("bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beer bottle.
        /// </summary>
        public static string beer_bottle {
            get {
                return ResourceManager.GetString("beer_bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beer pack.
        /// </summary>
        public static string beer_pack {
            get {
                return ResourceManager.GetString("beer_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze Bar.
        /// </summary>
        public static string bronzebar {
            get {
                return ResourceManager.GetString("bronzebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullpup rifle.
        /// </summary>
        public static string bullpup_rifle {
            get {
                return ResourceManager.GetString("bullpup_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullpup shotgun.
        /// </summary>
        public static string bullpup_shotgun {
            get {
                return ResourceManager.GetString("bullpup_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burger.
        /// </summary>
        public static string burger {
            get {
                return ResourceManager.GetString("burger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string camera {
            get {
                return ResourceManager.GetString("camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candies.
        /// </summary>
        public static string candy {
            get {
                return ResourceManager.GetString("candy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbine.
        /// </summary>
        public static string carbine_rifle {
            get {
                return ResourceManager.GetString("carbine_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cava bottle.
        /// </summary>
        public static string cava_bottle {
            get {
                return ResourceManager.GetString("cava_bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedWood cigarettes.
        /// </summary>
        public static string cigarettes {
            get {
                return ResourceManager.GetString("cigarettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocain.
        /// </summary>
        public static string cocain {
            get {
                return ResourceManager.GetString("cocain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee.
        /// </summary>
        public static string coffee {
            get {
                return ResourceManager.GetString("coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FunCola.
        /// </summary>
        public static string cola {
            get {
                return ResourceManager.GetString("cola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat PDW.
        /// </summary>
        public static string combat_pdw {
            get {
                return ResourceManager.GetString("combat_pdw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact rifle.
        /// </summary>
        public static string compact_rifle {
            get {
                return ResourceManager.GetString("compact_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper.
        /// </summary>
        public static string copper {
            get {
                return ResourceManager.GetString("copper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper bar.
        /// </summary>
        public static string copperbar {
            get {
                return ResourceManager.GetString("copperbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crowbar.
        /// </summary>
        public static string crowbar {
            get {
                return ResourceManager.GetString("crowbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double barrel shotgun.
        /// </summary>
        public static string double_barrel_shotgun {
            get {
                return ResourceManager.GetString("double_barrel_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dufflebag.
        /// </summary>
        public static string dufflebag {
            get {
                return ResourceManager.GetString("dufflebag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy drink.
        /// </summary>
        public static string energy_drink {
            get {
                return ResourceManager.GetString("energy_drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extacy.
        /// </summary>
        public static string extacy {
            get {
                return ResourceManager.GetString("extacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish.
        /// </summary>
        public static string fish {
            get {
                return ResourceManager.GetString("fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing rod.
        /// </summary>
        public static string fishing_rod {
            get {
                return ResourceManager.GetString("fishing_rod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashlight.
        /// </summary>
        public static string flashlight {
            get {
                return ResourceManager.GetString("flashlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string gold {
            get {
                return ResourceManager.GetString("gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold bar.
        /// </summary>
        public static string goldbar {
            get {
                return ResourceManager.GetString("goldbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golf club.
        /// </summary>
        public static string golf_club {
            get {
                return ResourceManager.GetString("golf_club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hammer.
        /// </summary>
        public static string hammer {
            get {
                return ResourceManager.GetString("hammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatchet.
        /// </summary>
        public static string hatchet {
            get {
                return ResourceManager.GetString("hatchet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy pistol.
        /// </summary>
        public static string heavy_pistol {
            get {
                return ResourceManager.GetString("heavy_pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy shotgun.
        /// </summary>
        public static string heavy_shotgun {
            get {
                return ResourceManager.GetString("heavy_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy sniper rifle.
        /// </summary>
        public static string heavy_sniper {
            get {
                return ResourceManager.GetString("heavy_sniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemp.
        /// </summary>
        public static string hemp {
            get {
                return ResourceManager.GetString("hemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot dog.
        /// </summary>
        public static string hotdog {
            get {
                return ResourceManager.GetString("hotdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron.
        /// </summary>
        public static string iron {
            get {
                return ResourceManager.GetString("iron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron Bar.
        /// </summary>
        public static string ironbar {
            get {
                return ResourceManager.GetString("ironbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jackhammer.
        /// </summary>
        public static string jackhammer {
            get {
                return ResourceManager.GetString("jackhammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerrycan.
        /// </summary>
        public static string jerrycan {
            get {
                return ResourceManager.GetString("jerrycan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juice.
        /// </summary>
        public static string juice {
            get {
                return ResourceManager.GetString("juice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knife.
        /// </summary>
        public static string knife {
            get {
                return ResourceManager.GetString("knife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knuckle duster.
        /// </summary>
        public static string knucle_duster {
            get {
                return ResourceManager.GetString("knucle_duster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead.
        /// </summary>
        public static string lead {
            get {
                return ResourceManager.GetString("lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Bar.
        /// </summary>
        public static string leadbar {
            get {
                return ResourceManager.GetString("leadbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocain Leaf.
        /// </summary>
        public static string leaf {
            get {
                return ResourceManager.GetString("leaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine pistol.
        /// </summary>
        public static string machine_pistol {
            get {
                return ResourceManager.GetString("machine_pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marksman rifle.
        /// </summary>
        public static string marksman_rifle {
            get {
                return ResourceManager.GetString("marksman_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauretic Acid.
        /// </summary>
        public static string maureticacid {
            get {
                return ResourceManager.GetString("maureticacid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medkit.
        /// </summary>
        public static string medkit {
            get {
                return ResourceManager.GetString("medkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meth.
        /// </summary>
        public static string meth {
            get {
                return ResourceManager.GetString("meth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micro SMG.
        /// </summary>
        public static string micro_smg {
            get {
                return ResourceManager.GetString("micro_smg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickaxe.
        /// </summary>
        public static string pickaxe {
            get {
                return ResourceManager.GetString("pickaxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistol.
        /// </summary>
        public static string pistol {
            get {
                return ResourceManager.GetString("pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistol 50.
        /// </summary>
        public static string pistol_50 {
            get {
                return ResourceManager.GetString("pistol_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistol ammunition.
        /// </summary>
        public static string pistol_ammo {
            get {
                return ResourceManager.GetString("pistol_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pump shotgun.
        /// </summary>
        public static string pump_shotgun {
            get {
                return ResourceManager.GetString("pump_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolver.
        /// </summary>
        public static string revolver {
            get {
                return ResourceManager.GetString("revolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assault rifle ammunition.
        /// </summary>
        public static string rifle_ammo {
            get {
                return ResourceManager.GetString("rifle_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandwich.
        /// </summary>
        public static string sandwich {
            get {
                return ResourceManager.GetString("sandwich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sawn-off shotgun.
        /// </summary>
        public static string sawn_off_shotgun {
            get {
                return ResourceManager.GetString("sawn_off_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shotgun ammunition.
        /// </summary>
        public static string shotgun_ammo {
            get {
                return ResourceManager.GetString("shotgun_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smartphone.
        /// </summary>
        public static string smartphone {
            get {
                return ResourceManager.GetString("smartphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMG.
        /// </summary>
        public static string smg {
            get {
                return ResourceManager.GetString("smg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine gun ammunition.
        /// </summary>
        public static string smg_ammo {
            get {
                return ResourceManager.GetString("smg_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper rifle ammunition.
        /// </summary>
        public static string sniper_ammo {
            get {
                return ResourceManager.GetString("sniper_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper rifle.
        /// </summary>
        public static string sniper_rifle {
            get {
                return ResourceManager.GetString("sniper_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sodium.
        /// </summary>
        public static string sodium {
            get {
                return ResourceManager.GetString("sodium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special carbine.
        /// </summary>
        public static string special_carbine {
            get {
                return ResourceManager.GetString("special_carbine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stolen items.
        /// </summary>
        public static string stolen_items {
            get {
                return ResourceManager.GetString("stolen_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulfuric Acid.
        /// </summary>
        public static string sufluricacid {
            get {
                return ResourceManager.GetString("sufluricacid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switchblade.
        /// </summary>
        public static string switchblade {
            get {
                return ResourceManager.GetString("switchblade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin ore.
        /// </summary>
        public static string tin {
            get {
                return ResourceManager.GetString("tin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin Bar.
        /// </summary>
        public static string tinbar {
            get {
                return ResourceManager.GetString("tinbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walkie-Talkie.
        /// </summary>
        public static string walkie {
            get {
                return ResourceManager.GetString("walkie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weed.
        /// </summary>
        public static string weed {
            get {
                return ResourceManager.GetString("weed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planting Pot.
        /// </summary>
        public static string weedpot {
            get {
                return ResourceManager.GetString("weedpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weed Seeds.
        /// </summary>
        public static string weedseed {
            get {
                return ResourceManager.GetString("weedseed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrench.
        /// </summary>
        public static string wrench {
            get {
                return ResourceManager.GetString("wrench", resourceCulture);
            }
        }
    }
}
